-- ============================================================================
-- Templates v2: Properly fitted layouts for each screen size
-- Each layout uses ~4% margin, name at top 20%, price fills 40-50%, unit at bottom
-- ============================================================================

DELETE FROM template_variants;
DELETE FROM templates;

INSERT INTO templates (id, name, description, kind, created_at) VALUES
  ('tpl_standard',  'Standard price tag', 'Clean layout with product name, divider, price and unit.',                          'price', '2025-01-01T00:00:00Z'),
  ('tpl_promo',     'Promo highlight',    'Red sale banner at top with discount badge. For promotions.',                        'promo', '2025-01-01T00:00:00Z'),
  ('tpl_minimal',   'Minimal',            'Centered design — large price, minimal clutter.',                                   'price', '2025-01-01T00:00:00Z'),
  ('tpl_info',      'Info card',          'Category + name on left, large price on right. For detailed shelves.',              'info',  '2025-01-01T00:00:00Z'),
  ('tpl_bold',      'Bold shelf',         'Dark background, white text. Maximum shelf visibility.',                            'price', '2025-01-01T00:00:00Z');

-- ============================================================================
-- STANDARD — name / line / price / unit
-- Layout: name top ~18%, line at ~28%, price centered ~55%, unit ~88%
-- ============================================================================
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
-- 1.54" 152×152
('tv_std_154','tpl_standard','MTAG15',152,152,
'{"width":152,"height":152,"background":"white","elements":[{"type":"text","field":"name","x":8,"y":22,"fontSize":13,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":136},{"type":"line","x1":8,"y1":44,"x2":144,"y2":44,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":8,"y":96,"fontSize":34,"fontWeight":"bold","align":"center","color":"black","w":136},{"type":"text","field":"unit","x":8,"y":132,"fontSize":10,"fontWeight":"normal","align":"center","color":"black","w":136}]}'),
-- 2.13" 250×122
('tv_std_213','tpl_standard','ESL-2.13',250,122,
'{"width":250,"height":122,"background":"white","elements":[{"type":"text","field":"name","x":10,"y":20,"fontSize":14,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":230},{"type":"line","x1":10,"y1":32,"x2":240,"y2":32,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":10,"y":78,"fontSize":34,"fontWeight":"bold","align":"center","color":"black","w":230},{"type":"text","field":"unit","x":10,"y":108,"fontSize":10,"fontWeight":"normal","align":"center","color":"black","w":230}]}'),
-- 2.66" 296×152
('tv_std_266','tpl_standard','DS026F',296,152,
'{"width":296,"height":152,"background":"white","elements":[{"type":"text","field":"name","x":12,"y":24,"fontSize":15,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":272},{"type":"line","x1":12,"y1":38,"x2":284,"y2":38,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":12,"y":96,"fontSize":40,"fontWeight":"bold","align":"center","color":"black","w":272},{"type":"text","field":"unit","x":12,"y":136,"fontSize":11,"fontWeight":"normal","align":"center","color":"black","w":272}]}'),
-- 2.67" 384×200
('tv_std_267','tpl_standard','DS027Q',384,200,
'{"width":384,"height":200,"background":"white","elements":[{"type":"text","field":"name","x":16,"y":28,"fontSize":17,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":352},{"type":"line","x1":16,"y1":46,"x2":368,"y2":46,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":16,"y":124,"fontSize":48,"fontWeight":"bold","align":"center","color":"black","w":352},{"type":"text","field":"unit","x":16,"y":176,"fontSize":13,"fontWeight":"normal","align":"center","color":"black","w":352}]}'),
-- 2.9" 296×128
('tv_std_290','tpl_standard','ESL-2.9',296,128,
'{"width":296,"height":128,"background":"white","elements":[{"type":"text","field":"name","x":12,"y":20,"fontSize":14,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":272},{"type":"line","x1":12,"y1":34,"x2":284,"y2":34,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":12,"y":82,"fontSize":34,"fontWeight":"bold","align":"center","color":"black","w":272},{"type":"text","field":"unit","x":12,"y":114,"fontSize":10,"fontWeight":"normal","align":"center","color":"black","w":272}]}'),
-- 3.5" 384×184
('tv_std_350','tpl_standard','DS035Q',384,184,
'{"width":384,"height":184,"background":"white","elements":[{"type":"text","field":"name","x":16,"y":26,"fontSize":16,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":352},{"type":"line","x1":16,"y1":42,"x2":368,"y2":42,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":16,"y":116,"fontSize":46,"fontWeight":"bold","align":"center","color":"black","w":352},{"type":"text","field":"unit","x":16,"y":166,"fontSize":12,"fontWeight":"normal","align":"center","color":"black","w":352}]}'),
-- 4.2" 400×300
('tv_std_420','tpl_standard','ESL-4.2',400,300,
'{"width":400,"height":300,"background":"white","elements":[{"type":"text","field":"name","x":16,"y":36,"fontSize":20,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":368},{"type":"line","x1":16,"y1":68,"x2":384,"y2":68,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":16,"y":180,"fontSize":64,"fontWeight":"bold","align":"center","color":"black","w":368},{"type":"text","field":"unit","x":16,"y":264,"fontSize":15,"fontWeight":"normal","align":"center","color":"black","w":368}]}'),
-- 4.3" 522×152
('tv_std_430','tpl_standard','DS043Q',522,152,
'{"width":522,"height":152,"background":"white","elements":[{"type":"text","field":"name","x":16,"y":24,"fontSize":16,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":230},{"type":"line","x1":260,"y1":12,"x2":260,"y2":140,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":276,"y":84,"fontSize":44,"fontWeight":"bold","align":"center","color":"black","w":230},{"type":"text","field":"unit","x":276,"y":128,"fontSize":12,"fontWeight":"normal","align":"center","color":"black","w":230}]}'),
-- 5.83" 648×480
('tv_std_583','tpl_standard','ESL-5.83',648,480,
'{"width":648,"height":480,"background":"white","elements":[{"type":"text","field":"name","x":24,"y":48,"fontSize":26,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":600},{"type":"line","x1":24,"y1":92,"x2":624,"y2":92,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":24,"y":288,"fontSize":80,"fontWeight":"bold","align":"center","color":"black","w":600},{"type":"text","field":"unit","x":24,"y":420,"fontSize":18,"fontWeight":"normal","align":"center","color":"black","w":600}]}'),
-- 7.5" 800×480
('tv_std_750','tpl_standard','ESL-7.5',800,480,
'{"width":800,"height":480,"background":"white","elements":[{"type":"text","field":"name","x":32,"y":48,"fontSize":28,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":736},{"type":"line","x1":32,"y1":92,"x2":768,"y2":92,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":32,"y":288,"fontSize":84,"fontWeight":"bold","align":"center","color":"black","w":736},{"type":"text","field":"unit","x":32,"y":420,"fontSize":20,"fontWeight":"normal","align":"center","color":"black","w":736}]}'),
-- 11.6" 960×640
('tv_std_116','tpl_standard','ESL-11.6',960,640,
'{"width":960,"height":640,"background":"white","elements":[{"type":"text","field":"name","x":40,"y":60,"fontSize":34,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":880},{"type":"line","x1":40,"y1":120,"x2":920,"y2":120,"color":"black","strokeWidth":2},{"type":"text","field":"price","x":40,"y":380,"fontSize":100,"fontWeight":"bold","align":"center","color":"black","w":880},{"type":"text","field":"unit","x":40,"y":556,"fontSize":24,"fontWeight":"normal","align":"center","color":"black","w":880}]}');

-- ============================================================================
-- PROMO — red banner / name / price + discount badge
-- Banner ~22% height, name below, price+discount centered
-- ============================================================================
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_prm_154','tpl_promo','MTAG15',152,152,
'{"width":152,"height":152,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":152,"h":32,"color":"red"},{"type":"label","text":"SALE","x":8,"y":23,"fontSize":14,"fontWeight":"bold","color":"white"},{"type":"text","field":"name","x":8,"y":56,"fontSize":12,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":136},{"type":"text","field":"price","x":8,"y":108,"fontSize":30,"fontWeight":"bold","align":"center","color":"black","w":136},{"type":"label","text":"20% OFF","x":8,"y":140,"fontSize":10,"fontWeight":"bold","color":"red"}]}'),
('tv_prm_213','tpl_promo','ESL-2.13',250,122,
'{"width":250,"height":122,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":250,"h":28,"color":"red"},{"type":"label","text":"SALE","x":10,"y":20,"fontSize":13,"fontWeight":"bold","color":"white"},{"type":"text","field":"name","x":10,"y":46,"fontSize":13,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":230},{"type":"text","field":"price","x":10,"y":86,"fontSize":28,"fontWeight":"bold","align":"left","color":"black"},{"type":"label","text":"20% OFF","x":150,"y":86,"fontSize":11,"fontWeight":"bold","color":"red"}]}'),
('tv_prm_266','tpl_promo','DS026F',296,152,
'{"width":296,"height":152,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":296,"h":32,"color":"red"},{"type":"label","text":"SALE","x":12,"y":23,"fontSize":14,"fontWeight":"bold","color":"white"},{"type":"text","field":"name","x":12,"y":52,"fontSize":14,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":272},{"type":"text","field":"price","x":12,"y":104,"fontSize":34,"fontWeight":"bold","align":"left","color":"black"},{"type":"label","text":"20% OFF","x":180,"y":104,"fontSize":12,"fontWeight":"bold","color":"red"}]}'),
('tv_prm_267','tpl_promo','DS027Q',384,200,
'{"width":384,"height":200,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":384,"h":40,"color":"red"},{"type":"label","text":"SALE","x":16,"y":28,"fontSize":16,"fontWeight":"bold","color":"white"},{"type":"text","field":"name","x":16,"y":62,"fontSize":16,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":352},{"type":"text","field":"price","x":16,"y":130,"fontSize":42,"fontWeight":"bold","align":"left","color":"black"},{"type":"label","text":"20% OFF","x":230,"y":130,"fontSize":14,"fontWeight":"bold","color":"red"}]}'),
('tv_prm_290','tpl_promo','ESL-2.9',296,128,
'{"width":296,"height":128,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":296,"h":28,"color":"red"},{"type":"label","text":"SALE","x":12,"y":20,"fontSize":13,"fontWeight":"bold","color":"white"},{"type":"text","field":"name","x":12,"y":44,"fontSize":13,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":272},{"type":"text","field":"price","x":12,"y":86,"fontSize":30,"fontWeight":"bold","align":"left","color":"black"},{"type":"label","text":"20% OFF","x":160,"y":86,"fontSize":11,"fontWeight":"bold","color":"red"}]}'),
('tv_prm_350','tpl_promo','DS035Q',384,184,
'{"width":384,"height":184,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":384,"h":36,"color":"red"},{"type":"label","text":"SALE","x":16,"y":26,"fontSize":15,"fontWeight":"bold","color":"white"},{"type":"text","field":"name","x":16,"y":58,"fontSize":15,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":352},{"type":"text","field":"price","x":16,"y":122,"fontSize":40,"fontWeight":"bold","align":"left","color":"black"},{"type":"label","text":"20% OFF","x":220,"y":122,"fontSize":13,"fontWeight":"bold","color":"red"}]}'),
('tv_prm_420','tpl_promo','ESL-4.2',400,300,
'{"width":400,"height":300,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":400,"h":48,"color":"red"},{"type":"label","text":"SALE","x":16,"y":34,"fontSize":20,"fontWeight":"bold","color":"white"},{"type":"text","field":"name","x":16,"y":76,"fontSize":18,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":368},{"type":"text","field":"price","x":16,"y":190,"fontSize":56,"fontWeight":"bold","align":"center","color":"black","w":368},{"type":"label","text":"20% OFF","x":16,"y":264,"fontSize":16,"fontWeight":"bold","color":"red"}]}'),
('tv_prm_430','tpl_promo','DS043Q',522,152,
'{"width":522,"height":152,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":522,"h":30,"color":"red"},{"type":"label","text":"SALE","x":16,"y":22,"fontSize":13,"fontWeight":"bold","color":"white"},{"type":"text","field":"name","x":16,"y":50,"fontSize":14,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":230},{"type":"text","field":"price","x":276,"y":86,"fontSize":42,"fontWeight":"bold","align":"center","color":"black","w":230},{"type":"label","text":"20% OFF","x":276,"y":130,"fontSize":12,"fontWeight":"bold","color":"red"}]}'),
('tv_prm_583','tpl_promo','ESL-5.83',648,480,
'{"width":648,"height":480,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":648,"h":64,"color":"red"},{"type":"label","text":"SALE","x":24,"y":44,"fontSize":26,"fontWeight":"bold","color":"white"},{"type":"text","field":"name","x":24,"y":98,"fontSize":22,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":600},{"type":"text","field":"price","x":24,"y":288,"fontSize":72,"fontWeight":"bold","align":"center","color":"black","w":600},{"type":"label","text":"20% OFF","x":24,"y":400,"fontSize":20,"fontWeight":"bold","color":"red"}]}'),
('tv_prm_750','tpl_promo','ESL-7.5',800,480,
'{"width":800,"height":480,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":800,"h":64,"color":"red"},{"type":"label","text":"SALE","x":32,"y":44,"fontSize":28,"fontWeight":"bold","color":"white"},{"type":"text","field":"name","x":32,"y":100,"fontSize":24,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":736},{"type":"text","field":"price","x":32,"y":288,"fontSize":80,"fontWeight":"bold","align":"center","color":"black","w":736},{"type":"label","text":"20% OFF","x":32,"y":408,"fontSize":22,"fontWeight":"bold","color":"red"}]}'),
('tv_prm_116','tpl_promo','ESL-11.6',960,640,
'{"width":960,"height":640,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":960,"h":80,"color":"red"},{"type":"label","text":"SALE","x":40,"y":56,"fontSize":32,"fontWeight":"bold","color":"white"},{"type":"text","field":"name","x":40,"y":124,"fontSize":28,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":880},{"type":"text","field":"price","x":40,"y":376,"fontSize":96,"fontWeight":"bold","align":"center","color":"black","w":880},{"type":"label","text":"20% OFF","x":40,"y":530,"fontSize":26,"fontWeight":"bold","color":"red"}]}');

-- ============================================================================
-- MINIMAL — centered: name / big price / unit
-- ============================================================================
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_min_154','tpl_minimal','MTAG15',152,152,
'{"width":152,"height":152,"background":"white","elements":[{"type":"text","field":"name","x":8,"y":36,"fontSize":12,"fontWeight":"normal","align":"center","color":"black","maxLines":2,"w":136},{"type":"text","field":"price","x":8,"y":96,"fontSize":36,"fontWeight":"bold","align":"center","color":"black","w":136},{"type":"text","field":"unit","x":8,"y":134,"fontSize":10,"fontWeight":"normal","align":"center","color":"black","w":136}]}'),
('tv_min_213','tpl_minimal','ESL-2.13',250,122,
'{"width":250,"height":122,"background":"white","elements":[{"type":"text","field":"name","x":10,"y":24,"fontSize":12,"fontWeight":"normal","align":"center","color":"black","maxLines":1,"w":230},{"type":"text","field":"price","x":10,"y":76,"fontSize":36,"fontWeight":"bold","align":"center","color":"black","w":230},{"type":"text","field":"unit","x":10,"y":110,"fontSize":10,"fontWeight":"normal","align":"center","color":"black","w":230}]}'),
('tv_min_266','tpl_minimal','DS026F',296,152,
'{"width":296,"height":152,"background":"white","elements":[{"type":"text","field":"name","x":12,"y":30,"fontSize":13,"fontWeight":"normal","align":"center","color":"black","maxLines":1,"w":272},{"type":"text","field":"price","x":12,"y":94,"fontSize":42,"fontWeight":"bold","align":"center","color":"black","w":272},{"type":"text","field":"unit","x":12,"y":136,"fontSize":11,"fontWeight":"normal","align":"center","color":"black","w":272}]}'),
('tv_min_267','tpl_minimal','DS027Q',384,200,
'{"width":384,"height":200,"background":"white","elements":[{"type":"text","field":"name","x":16,"y":36,"fontSize":14,"fontWeight":"normal","align":"center","color":"black","maxLines":1,"w":352},{"type":"text","field":"price","x":16,"y":120,"fontSize":50,"fontWeight":"bold","align":"center","color":"black","w":352},{"type":"text","field":"unit","x":16,"y":178,"fontSize":12,"fontWeight":"normal","align":"center","color":"black","w":352}]}'),
('tv_min_290','tpl_minimal','ESL-2.9',296,128,
'{"width":296,"height":128,"background":"white","elements":[{"type":"text","field":"name","x":12,"y":24,"fontSize":12,"fontWeight":"normal","align":"center","color":"black","maxLines":1,"w":272},{"type":"text","field":"price","x":12,"y":78,"fontSize":36,"fontWeight":"bold","align":"center","color":"black","w":272},{"type":"text","field":"unit","x":12,"y":114,"fontSize":10,"fontWeight":"normal","align":"center","color":"black","w":272}]}'),
('tv_min_350','tpl_minimal','DS035Q',384,184,
'{"width":384,"height":184,"background":"white","elements":[{"type":"text","field":"name","x":16,"y":32,"fontSize":13,"fontWeight":"normal","align":"center","color":"black","maxLines":1,"w":352},{"type":"text","field":"price","x":16,"y":112,"fontSize":46,"fontWeight":"bold","align":"center","color":"black","w":352},{"type":"text","field":"unit","x":16,"y":168,"fontSize":12,"fontWeight":"normal","align":"center","color":"black","w":352}]}'),
('tv_min_420','tpl_minimal','ESL-4.2',400,300,
'{"width":400,"height":300,"background":"white","elements":[{"type":"text","field":"name","x":16,"y":50,"fontSize":17,"fontWeight":"normal","align":"center","color":"black","maxLines":2,"w":368},{"type":"text","field":"price","x":16,"y":178,"fontSize":64,"fontWeight":"bold","align":"center","color":"black","w":368},{"type":"text","field":"unit","x":16,"y":262,"fontSize":14,"fontWeight":"normal","align":"center","color":"black","w":368}]}'),
('tv_min_430','tpl_minimal','DS043Q',522,152,
'{"width":522,"height":152,"background":"white","elements":[{"type":"text","field":"name","x":16,"y":28,"fontSize":14,"fontWeight":"normal","align":"left","color":"black","maxLines":2,"w":230},{"type":"text","field":"price","x":276,"y":88,"fontSize":44,"fontWeight":"bold","align":"center","color":"black","w":230},{"type":"text","field":"unit","x":276,"y":134,"fontSize":11,"fontWeight":"normal","align":"center","color":"black","w":230}]}'),
('tv_min_583','tpl_minimal','ESL-5.83',648,480,
'{"width":648,"height":480,"background":"white","elements":[{"type":"text","field":"name","x":24,"y":80,"fontSize":22,"fontWeight":"normal","align":"center","color":"black","maxLines":2,"w":600},{"type":"text","field":"price","x":24,"y":280,"fontSize":76,"fontWeight":"bold","align":"center","color":"black","w":600},{"type":"text","field":"unit","x":24,"y":416,"fontSize":18,"fontWeight":"normal","align":"center","color":"black","w":600}]}'),
('tv_min_750','tpl_minimal','ESL-7.5',800,480,
'{"width":800,"height":480,"background":"white","elements":[{"type":"text","field":"name","x":32,"y":72,"fontSize":24,"fontWeight":"normal","align":"center","color":"black","maxLines":2,"w":736},{"type":"text","field":"price","x":32,"y":280,"fontSize":84,"fontWeight":"bold","align":"center","color":"black","w":736},{"type":"text","field":"unit","x":32,"y":416,"fontSize":20,"fontWeight":"normal","align":"center","color":"black","w":736}]}'),
('tv_min_116','tpl_minimal','ESL-11.6',960,640,
'{"width":960,"height":640,"background":"white","elements":[{"type":"text","field":"name","x":40,"y":100,"fontSize":28,"fontWeight":"normal","align":"center","color":"black","maxLines":2,"w":880},{"type":"text","field":"price","x":40,"y":372,"fontSize":100,"fontWeight":"bold","align":"center","color":"black","w":880},{"type":"text","field":"unit","x":40,"y":554,"fontSize":24,"fontWeight":"normal","align":"center","color":"black","w":880}]}');

-- ============================================================================
-- INFO — category top-left / name / divider / price right-aligned
-- ============================================================================
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_inf_154','tpl_info','MTAG15',152,152,
'{"width":152,"height":152,"background":"white","elements":[{"type":"text","field":"category","x":8,"y":16,"fontSize":9,"fontWeight":"normal","align":"left","color":"black"},{"type":"text","field":"name","x":8,"y":36,"fontSize":14,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":136},{"type":"line","x1":8,"y1":62,"x2":144,"y2":62,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":8,"y":112,"fontSize":32,"fontWeight":"bold","align":"right","color":"black","w":136},{"type":"text","field":"unit","x":8,"y":138,"fontSize":9,"fontWeight":"normal","align":"right","color":"black","w":136}]}'),
('tv_inf_213','tpl_info','ESL-2.13',250,122,
'{"width":250,"height":122,"background":"white","elements":[{"type":"text","field":"category","x":10,"y":14,"fontSize":9,"fontWeight":"normal","align":"left","color":"black"},{"type":"text","field":"name","x":10,"y":30,"fontSize":14,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":230},{"type":"line","x1":10,"y1":42,"x2":240,"y2":42,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":10,"y":86,"fontSize":32,"fontWeight":"bold","align":"right","color":"black","w":230},{"type":"text","field":"unit","x":10,"y":108,"fontSize":10,"fontWeight":"normal","align":"right","color":"black","w":230}]}'),
('tv_inf_266','tpl_info','DS026F',296,152,
'{"width":296,"height":152,"background":"white","elements":[{"type":"text","field":"category","x":12,"y":16,"fontSize":10,"fontWeight":"normal","align":"left","color":"black"},{"type":"text","field":"name","x":12,"y":34,"fontSize":15,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":272},{"type":"line","x1":12,"y1":50,"x2":284,"y2":50,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":12,"y":104,"fontSize":36,"fontWeight":"bold","align":"right","color":"black","w":272},{"type":"text","field":"unit","x":12,"y":134,"fontSize":11,"fontWeight":"normal","align":"right","color":"black","w":272}]}'),
('tv_inf_267','tpl_info','DS027Q',384,200,
'{"width":384,"height":200,"background":"white","elements":[{"type":"text","field":"category","x":16,"y":18,"fontSize":11,"fontWeight":"normal","align":"left","color":"black"},{"type":"text","field":"name","x":16,"y":38,"fontSize":17,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":352},{"type":"line","x1":16,"y1":56,"x2":368,"y2":56,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":16,"y":130,"fontSize":46,"fontWeight":"bold","align":"right","color":"black","w":352},{"type":"text","field":"unit","x":16,"y":178,"fontSize":12,"fontWeight":"normal","align":"right","color":"black","w":352}]}'),
('tv_inf_290','tpl_info','ESL-2.9',296,128,
'{"width":296,"height":128,"background":"white","elements":[{"type":"text","field":"category","x":12,"y":14,"fontSize":9,"fontWeight":"normal","align":"left","color":"black"},{"type":"text","field":"name","x":12,"y":30,"fontSize":14,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":272},{"type":"line","x1":12,"y1":44,"x2":284,"y2":44,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":12,"y":86,"fontSize":30,"fontWeight":"bold","align":"right","color":"black","w":272},{"type":"text","field":"unit","x":12,"y":114,"fontSize":10,"fontWeight":"normal","align":"right","color":"black","w":272}]}'),
('tv_inf_350','tpl_info','DS035Q',384,184,
'{"width":384,"height":184,"background":"white","elements":[{"type":"text","field":"category","x":16,"y":16,"fontSize":10,"fontWeight":"normal","align":"left","color":"black"},{"type":"text","field":"name","x":16,"y":36,"fontSize":16,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":352},{"type":"line","x1":16,"y1":52,"x2":368,"y2":52,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":16,"y":120,"fontSize":42,"fontWeight":"bold","align":"right","color":"black","w":352},{"type":"text","field":"unit","x":16,"y":166,"fontSize":12,"fontWeight":"normal","align":"right","color":"black","w":352}]}'),
('tv_inf_420','tpl_info','ESL-4.2',400,300,
'{"width":400,"height":300,"background":"white","elements":[{"type":"text","field":"category","x":16,"y":24,"fontSize":12,"fontWeight":"normal","align":"left","color":"black"},{"type":"text","field":"name","x":16,"y":50,"fontSize":20,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":368},{"type":"line","x1":16,"y1":84,"x2":384,"y2":84,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":16,"y":194,"fontSize":60,"fontWeight":"bold","align":"right","color":"black","w":368},{"type":"text","field":"unit","x":16,"y":266,"fontSize":14,"fontWeight":"normal","align":"right","color":"black","w":368}]}'),
('tv_inf_430','tpl_info','DS043Q',522,152,
'{"width":522,"height":152,"background":"white","elements":[{"type":"text","field":"category","x":16,"y":16,"fontSize":10,"fontWeight":"normal","align":"left","color":"black"},{"type":"text","field":"name","x":16,"y":34,"fontSize":15,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":230},{"type":"line","x1":260,"y1":12,"x2":260,"y2":140,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":276,"y":80,"fontSize":42,"fontWeight":"bold","align":"center","color":"black","w":230},{"type":"text","field":"unit","x":276,"y":128,"fontSize":12,"fontWeight":"normal","align":"center","color":"black","w":230}]}'),
('tv_inf_583','tpl_info','ESL-5.83',648,480,
'{"width":648,"height":480,"background":"white","elements":[{"type":"text","field":"category","x":24,"y":32,"fontSize":15,"fontWeight":"normal","align":"left","color":"black"},{"type":"text","field":"name","x":24,"y":64,"fontSize":24,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":600},{"type":"line","x1":24,"y1":110,"x2":624,"y2":110,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":24,"y":300,"fontSize":72,"fontWeight":"bold","align":"right","color":"black","w":600},{"type":"text","field":"unit","x":24,"y":416,"fontSize":18,"fontWeight":"normal","align":"right","color":"black","w":600}]}'),
('tv_inf_750','tpl_info','ESL-7.5',800,480,
'{"width":800,"height":480,"background":"white","elements":[{"type":"text","field":"category","x":32,"y":32,"fontSize":16,"fontWeight":"normal","align":"left","color":"black"},{"type":"text","field":"name","x":32,"y":64,"fontSize":26,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":736},{"type":"line","x1":32,"y1":112,"x2":768,"y2":112,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":32,"y":300,"fontSize":80,"fontWeight":"bold","align":"right","color":"black","w":736},{"type":"text","field":"unit","x":32,"y":420,"fontSize":20,"fontWeight":"normal","align":"right","color":"black","w":736}]}'),
('tv_inf_116','tpl_info','ESL-11.6',960,640,
'{"width":960,"height":640,"background":"white","elements":[{"type":"text","field":"category","x":40,"y":40,"fontSize":20,"fontWeight":"normal","align":"left","color":"black"},{"type":"text","field":"name","x":40,"y":78,"fontSize":32,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":880},{"type":"line","x1":40,"y1":140,"x2":920,"y2":140,"color":"black","strokeWidth":2},{"type":"text","field":"price","x":40,"y":388,"fontSize":96,"fontWeight":"bold","align":"right","color":"black","w":880},{"type":"text","field":"unit","x":40,"y":556,"fontSize":24,"fontWeight":"normal","align":"right","color":"black","w":880}]}');

-- ============================================================================
-- BOLD — dark background, white centered text
-- ============================================================================
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_bld_154','tpl_bold','MTAG15',152,152,
'{"width":152,"height":152,"background":"black","elements":[{"type":"text","field":"name","x":8,"y":36,"fontSize":12,"fontWeight":"normal","align":"center","color":"white","maxLines":2,"w":136},{"type":"text","field":"price","x":8,"y":96,"fontSize":36,"fontWeight":"bold","align":"center","color":"white","w":136},{"type":"text","field":"unit","x":8,"y":134,"fontSize":10,"fontWeight":"normal","align":"center","color":"white","w":136}]}'),
('tv_bld_213','tpl_bold','ESL-2.13',250,122,
'{"width":250,"height":122,"background":"black","elements":[{"type":"text","field":"name","x":10,"y":24,"fontSize":12,"fontWeight":"normal","align":"center","color":"white","maxLines":1,"w":230},{"type":"text","field":"price","x":10,"y":76,"fontSize":36,"fontWeight":"bold","align":"center","color":"white","w":230},{"type":"text","field":"unit","x":10,"y":110,"fontSize":10,"fontWeight":"normal","align":"center","color":"white","w":230}]}'),
('tv_bld_266','tpl_bold','DS026F',296,152,
'{"width":296,"height":152,"background":"black","elements":[{"type":"text","field":"name","x":12,"y":30,"fontSize":13,"fontWeight":"normal","align":"center","color":"white","maxLines":1,"w":272},{"type":"text","field":"price","x":12,"y":94,"fontSize":42,"fontWeight":"bold","align":"center","color":"white","w":272},{"type":"text","field":"unit","x":12,"y":136,"fontSize":11,"fontWeight":"normal","align":"center","color":"white","w":272}]}'),
('tv_bld_267','tpl_bold','DS027Q',384,200,
'{"width":384,"height":200,"background":"black","elements":[{"type":"text","field":"name","x":16,"y":36,"fontSize":14,"fontWeight":"normal","align":"center","color":"white","maxLines":1,"w":352},{"type":"text","field":"price","x":16,"y":120,"fontSize":50,"fontWeight":"bold","align":"center","color":"white","w":352},{"type":"text","field":"unit","x":16,"y":178,"fontSize":12,"fontWeight":"normal","align":"center","color":"white","w":352}]}'),
('tv_bld_290','tpl_bold','ESL-2.9',296,128,
'{"width":296,"height":128,"background":"black","elements":[{"type":"text","field":"name","x":12,"y":24,"fontSize":12,"fontWeight":"normal","align":"center","color":"white","maxLines":1,"w":272},{"type":"text","field":"price","x":12,"y":78,"fontSize":36,"fontWeight":"bold","align":"center","color":"white","w":272},{"type":"text","field":"unit","x":12,"y":114,"fontSize":10,"fontWeight":"normal","align":"center","color":"white","w":272}]}'),
('tv_bld_350','tpl_bold','DS035Q',384,184,
'{"width":384,"height":184,"background":"black","elements":[{"type":"text","field":"name","x":16,"y":32,"fontSize":13,"fontWeight":"normal","align":"center","color":"white","maxLines":1,"w":352},{"type":"text","field":"price","x":16,"y":112,"fontSize":46,"fontWeight":"bold","align":"center","color":"white","w":352},{"type":"text","field":"unit","x":16,"y":168,"fontSize":12,"fontWeight":"normal","align":"center","color":"white","w":352}]}'),
('tv_bld_420','tpl_bold','ESL-4.2',400,300,
'{"width":400,"height":300,"background":"black","elements":[{"type":"text","field":"name","x":16,"y":50,"fontSize":17,"fontWeight":"normal","align":"center","color":"white","maxLines":2,"w":368},{"type":"text","field":"price","x":16,"y":178,"fontSize":64,"fontWeight":"bold","align":"center","color":"white","w":368},{"type":"text","field":"unit","x":16,"y":262,"fontSize":14,"fontWeight":"normal","align":"center","color":"white","w":368}]}'),
('tv_bld_430','tpl_bold','DS043Q',522,152,
'{"width":522,"height":152,"background":"black","elements":[{"type":"text","field":"name","x":16,"y":28,"fontSize":14,"fontWeight":"normal","align":"left","color":"white","maxLines":2,"w":230},{"type":"text","field":"price","x":276,"y":88,"fontSize":44,"fontWeight":"bold","align":"center","color":"white","w":230},{"type":"text","field":"unit","x":276,"y":134,"fontSize":11,"fontWeight":"normal","align":"center","color":"white","w":230}]}'),
('tv_bld_583','tpl_bold','ESL-5.83',648,480,
'{"width":648,"height":480,"background":"black","elements":[{"type":"text","field":"name","x":24,"y":80,"fontSize":22,"fontWeight":"normal","align":"center","color":"white","maxLines":2,"w":600},{"type":"text","field":"price","x":24,"y":280,"fontSize":76,"fontWeight":"bold","align":"center","color":"white","w":600},{"type":"text","field":"unit","x":24,"y":416,"fontSize":18,"fontWeight":"normal","align":"center","color":"white","w":600}]}'),
('tv_bld_750','tpl_bold','ESL-7.5',800,480,
'{"width":800,"height":480,"background":"black","elements":[{"type":"text","field":"name","x":32,"y":72,"fontSize":24,"fontWeight":"normal","align":"center","color":"white","maxLines":2,"w":736},{"type":"text","field":"price","x":32,"y":280,"fontSize":84,"fontWeight":"bold","align":"center","color":"white","w":736},{"type":"text","field":"unit","x":32,"y":416,"fontSize":20,"fontWeight":"normal","align":"center","color":"white","w":736}]}'),
('tv_bld_116','tpl_bold','ESL-11.6',960,640,
'{"width":960,"height":640,"background":"black","elements":[{"type":"text","field":"name","x":40,"y":100,"fontSize":28,"fontWeight":"normal","align":"center","color":"white","maxLines":2,"w":880},{"type":"text","field":"price","x":40,"y":372,"fontSize":100,"fontWeight":"bold","align":"center","color":"white","w":880},{"type":"text","field":"unit","x":40,"y":554,"fontSize":24,"fontWeight":"normal","align":"center","color":"white","w":880}]}');
