-- ============================================================================
-- Templates v3: 10 purpose-driven templates × 11 screen sizes = 110 variants
-- Each template has a distinct visual hierarchy ("first thing the eye sees")
-- Colors limited to ESL palette: black, white, red, yellow
-- ============================================================================

UPDATE products SET template_id = NULL WHERE template_id IS NOT NULL;
DELETE FROM template_variants;
DELETE FROM templates;

INSERT INTO templates (id, name, description, kind, created_at, purpose, when_to_use) VALUES
  ('tpl_classic',     'Classic Price',     'Clean everyday tag — name at top, large price, category and unit at bottom.',     'price',       '2025-01-01T00:00:00Z', 'Standard everyday price tag',                'Use for 80% of products — clean, legible layout with name, price and unit.'),
  ('tpl_big_price',   'Big Price',         'Price-dominant display — giant price fills 70% of screen, tiny name.',            'price',       '2025-01-01T00:00:00Z', 'Maximum price visibility',                   'Use when the price is the only thing that matters — impulse buys, price-sensitive items.'),
  ('tpl_promo',       'Promo / SALE',      'Promotional tag with red SALE banner, new price, and old price struck through.',  'promo',       '2025-01-01T00:00:00Z', 'Active promotions and sales',                'Use for time-limited promotions — shows SALE badge, new price, and crossed-out old price.'),
  ('tpl_discount',    'Discount Focus',    'Aggressive discount display — large percentage dominates the screen.',            'discount',    '2025-01-01T00:00:00Z', 'Highlight discount percentage',              'Use for aggressive discounts where the percentage off is the main draw — e.g. -30%, -50%.'),
  ('tpl_produce',     'Fresh Produce',     'Greengrocer-style tag — very large product name with clear per-kg pricing.',      'produce',     '2025-01-01T00:00:00Z', 'Fresh produce and market items',             'Use for fruits, vegetables, and bulk items — large name, clear unit pricing (per kg).'),
  ('tpl_minimal',     'Minimal',           'Ultra-clean luxury tag — name and price only, maximum whitespace.',               'minimal',     '2025-01-01T00:00:00Z', 'Clean luxury presentation',                  'Use for upscale stores or when you want a minimalist, premium feel — no clutter.'),
  ('tpl_info',        'Info Card',         'Information-dense tag — category, name, description, and price.',                 'info',        '2025-01-01T00:00:00Z', 'Products needing extra information',         'Use when products need a description or category context — supplements, specialty items.'),
  ('tpl_unit_price',  'Unit Price Focus',  'Unit-price dominant — per-kg/per-unit price large, regular price small.',         'unit_price',  '2025-01-01T00:00:00Z', 'Emphasize per-unit or per-kg pricing',       'Use for by-weight products in supermarkets — unit price is the star, total price secondary.'),
  ('tpl_status',      'Status Tag',        'Full-screen status badge — OUT OF STOCK, NEW, or LIMITED.',                       'status',      '2025-01-01T00:00:00Z', 'Product status announcements',               'Use when a product status matters more than its price — out of stock, new arrival, limited.'),
  ('tpl_image_price', 'Image + Price',     'Visual product display — image area on left, name and price on right.',           'image_price', '2025-01-01T00:00:00Z', 'Visual branded product display',             'Use for branded products where a product image adds value — cosmetics, electronics.');


-- ============================================================================
-- 1. CLASSIC PRICE — name top / line / price center / unit+category bottom
-- Eye catches: Product name first, then price
-- ============================================================================
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_cls_154','tpl_classic','MTAG15',152,152,
'{"width":152,"height":152,"background":"white","elements":[{"type":"text","field":"name","x":8,"y":22,"fontSize":13,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":136},{"type":"line","x1":8,"y1":44,"x2":144,"y2":44,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":8,"y":96,"fontSize":34,"fontWeight":"bold","align":"center","color":"black","w":136},{"type":"text","field":"category","x":8,"y":122,"fontSize":9,"fontWeight":"normal","align":"center","color":"black","w":136},{"type":"text","field":"unit","x":8,"y":140,"fontSize":10,"fontWeight":"normal","align":"center","color":"black","w":136}]}'),
('tv_cls_213','tpl_classic','ESL-2.13',250,122,
'{"width":250,"height":122,"background":"white","elements":[{"type":"text","field":"name","x":10,"y":20,"fontSize":14,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":230},{"type":"line","x1":10,"y1":32,"x2":240,"y2":32,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":10,"y":76,"fontSize":32,"fontWeight":"bold","align":"center","color":"black","w":230},{"type":"text","field":"category","x":10,"y":98,"fontSize":9,"fontWeight":"normal","align":"left","color":"black"},{"type":"text","field":"unit","x":10,"y":112,"fontSize":10,"fontWeight":"normal","align":"right","color":"black","w":230}]}'),
('tv_cls_266','tpl_classic','DS026F',296,152,
'{"width":296,"height":152,"background":"white","elements":[{"type":"text","field":"name","x":12,"y":24,"fontSize":15,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":272},{"type":"line","x1":12,"y1":38,"x2":284,"y2":38,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":12,"y":96,"fontSize":40,"fontWeight":"bold","align":"center","color":"black","w":272},{"type":"text","field":"category","x":12,"y":122,"fontSize":10,"fontWeight":"normal","align":"left","color":"black"},{"type":"text","field":"unit","x":12,"y":140,"fontSize":11,"fontWeight":"normal","align":"right","color":"black","w":272}]}'),
('tv_cls_267','tpl_classic','DS027Q',384,200,
'{"width":384,"height":200,"background":"white","elements":[{"type":"text","field":"name","x":16,"y":28,"fontSize":17,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":352},{"type":"line","x1":16,"y1":46,"x2":368,"y2":46,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":16,"y":124,"fontSize":48,"fontWeight":"bold","align":"center","color":"black","w":352},{"type":"text","field":"category","x":16,"y":160,"fontSize":11,"fontWeight":"normal","align":"left","color":"black"},{"type":"text","field":"unit","x":16,"y":180,"fontSize":13,"fontWeight":"normal","align":"right","color":"black","w":352}]}'),
('tv_cls_290','tpl_classic','ESL-2.9',296,128,
'{"width":296,"height":128,"background":"white","elements":[{"type":"text","field":"name","x":12,"y":20,"fontSize":14,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":272},{"type":"line","x1":12,"y1":34,"x2":284,"y2":34,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":12,"y":80,"fontSize":32,"fontWeight":"bold","align":"center","color":"black","w":272},{"type":"text","field":"category","x":12,"y":102,"fontSize":9,"fontWeight":"normal","align":"left","color":"black"},{"type":"text","field":"unit","x":12,"y":116,"fontSize":10,"fontWeight":"normal","align":"right","color":"black","w":272}]}'),
('tv_cls_350','tpl_classic','DS035Q',384,184,
'{"width":384,"height":184,"background":"white","elements":[{"type":"text","field":"name","x":16,"y":26,"fontSize":16,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":352},{"type":"line","x1":16,"y1":42,"x2":368,"y2":42,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":16,"y":114,"fontSize":46,"fontWeight":"bold","align":"center","color":"black","w":352},{"type":"text","field":"category","x":16,"y":148,"fontSize":10,"fontWeight":"normal","align":"left","color":"black"},{"type":"text","field":"unit","x":16,"y":168,"fontSize":12,"fontWeight":"normal","align":"right","color":"black","w":352}]}'),
('tv_cls_420','tpl_classic','ESL-4.2',400,300,
'{"width":400,"height":300,"background":"white","elements":[{"type":"text","field":"name","x":16,"y":36,"fontSize":20,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":368},{"type":"line","x1":16,"y1":68,"x2":384,"y2":68,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":16,"y":180,"fontSize":64,"fontWeight":"bold","align":"center","color":"black","w":368},{"type":"text","field":"category","x":16,"y":232,"fontSize":12,"fontWeight":"normal","align":"left","color":"black"},{"type":"text","field":"unit","x":16,"y":268,"fontSize":15,"fontWeight":"normal","align":"right","color":"black","w":368}]}'),
('tv_cls_430','tpl_classic','DS043Q',522,152,
'{"width":522,"height":152,"background":"white","elements":[{"type":"text","field":"name","x":16,"y":24,"fontSize":16,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":230},{"type":"line","x1":260,"y1":12,"x2":260,"y2":140,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":276,"y":84,"fontSize":44,"fontWeight":"bold","align":"center","color":"black","w":230},{"type":"text","field":"category","x":16,"y":100,"fontSize":10,"fontWeight":"normal","align":"left","color":"black"},{"type":"text","field":"unit","x":276,"y":128,"fontSize":12,"fontWeight":"normal","align":"center","color":"black","w":230}]}'),
('tv_cls_583','tpl_classic','ESL-5.83',648,480,
'{"width":648,"height":480,"background":"white","elements":[{"type":"text","field":"name","x":24,"y":48,"fontSize":26,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":600},{"type":"line","x1":24,"y1":92,"x2":624,"y2":92,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":24,"y":280,"fontSize":80,"fontWeight":"bold","align":"center","color":"black","w":600},{"type":"text","field":"category","x":24,"y":370,"fontSize":16,"fontWeight":"normal","align":"left","color":"black"},{"type":"text","field":"unit","x":24,"y":420,"fontSize":18,"fontWeight":"normal","align":"right","color":"black","w":600}]}'),
('tv_cls_750','tpl_classic','ESL-7.5',800,480,
'{"width":800,"height":480,"background":"white","elements":[{"type":"text","field":"name","x":32,"y":48,"fontSize":28,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":736},{"type":"line","x1":32,"y1":92,"x2":768,"y2":92,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":32,"y":280,"fontSize":84,"fontWeight":"bold","align":"center","color":"black","w":736},{"type":"text","field":"category","x":32,"y":370,"fontSize":17,"fontWeight":"normal","align":"left","color":"black"},{"type":"text","field":"unit","x":32,"y":420,"fontSize":20,"fontWeight":"normal","align":"right","color":"black","w":736}]}'),
('tv_cls_116','tpl_classic','ESL-11.6',960,640,
'{"width":960,"height":640,"background":"white","elements":[{"type":"text","field":"name","x":40,"y":60,"fontSize":34,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":880},{"type":"line","x1":40,"y1":120,"x2":920,"y2":120,"color":"black","strokeWidth":2},{"type":"text","field":"price","x":40,"y":376,"fontSize":100,"fontWeight":"bold","align":"center","color":"black","w":880},{"type":"text","field":"category","x":40,"y":490,"fontSize":20,"fontWeight":"normal","align":"left","color":"black"},{"type":"text","field":"unit","x":40,"y":556,"fontSize":24,"fontWeight":"normal","align":"right","color":"black","w":880}]}');


-- ============================================================================
-- 2. BIG PRICE — giant price (70% of screen), tiny name below
-- Eye catches: Price immediately
-- ============================================================================
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_bgp_154','tpl_big_price','MTAG15',152,152,
'{"width":152,"height":152,"background":"white","elements":[{"type":"text","field":"price","x":8,"y":100,"fontSize":52,"fontWeight":"bold","align":"center","color":"black","w":136},{"type":"text","field":"name","x":8,"y":136,"fontSize":10,"fontWeight":"normal","align":"center","color":"black","w":136,"maxLines":1}]}'),
('tv_bgp_213','tpl_big_price','ESL-2.13',250,122,
'{"width":250,"height":122,"background":"white","elements":[{"type":"text","field":"price","x":10,"y":80,"fontSize":52,"fontWeight":"bold","align":"center","color":"black","w":230},{"type":"text","field":"name","x":10,"y":110,"fontSize":10,"fontWeight":"normal","align":"center","color":"black","w":230,"maxLines":1}]}'),
('tv_bgp_266','tpl_big_price','DS026F',296,152,
'{"width":296,"height":152,"background":"white","elements":[{"type":"text","field":"price","x":12,"y":100,"fontSize":60,"fontWeight":"bold","align":"center","color":"black","w":272},{"type":"text","field":"name","x":12,"y":138,"fontSize":11,"fontWeight":"normal","align":"center","color":"black","w":272,"maxLines":1}]}'),
('tv_bgp_267','tpl_big_price','DS027Q',384,200,
'{"width":384,"height":200,"background":"white","elements":[{"type":"text","field":"price","x":16,"y":130,"fontSize":76,"fontWeight":"bold","align":"center","color":"black","w":352},{"type":"text","field":"name","x":16,"y":180,"fontSize":13,"fontWeight":"normal","align":"center","color":"black","w":352,"maxLines":1}]}'),
('tv_bgp_290','tpl_big_price','ESL-2.9',296,128,
'{"width":296,"height":128,"background":"white","elements":[{"type":"text","field":"price","x":12,"y":84,"fontSize":52,"fontWeight":"bold","align":"center","color":"black","w":272},{"type":"text","field":"name","x":12,"y":116,"fontSize":10,"fontWeight":"normal","align":"center","color":"black","w":272,"maxLines":1}]}'),
('tv_bgp_350','tpl_big_price','DS035Q',384,184,
'{"width":384,"height":184,"background":"white","elements":[{"type":"text","field":"price","x":16,"y":120,"fontSize":68,"fontWeight":"bold","align":"center","color":"black","w":352},{"type":"text","field":"name","x":16,"y":168,"fontSize":12,"fontWeight":"normal","align":"center","color":"black","w":352,"maxLines":1}]}'),
('tv_bgp_420','tpl_big_price','ESL-4.2',400,300,
'{"width":400,"height":300,"background":"white","elements":[{"type":"text","field":"price","x":16,"y":200,"fontSize":100,"fontWeight":"bold","align":"center","color":"black","w":368},{"type":"text","field":"name","x":16,"y":268,"fontSize":16,"fontWeight":"normal","align":"center","color":"black","w":368,"maxLines":1}]}'),
('tv_bgp_430','tpl_big_price','DS043Q',522,152,
'{"width":522,"height":152,"background":"white","elements":[{"type":"text","field":"price","x":16,"y":100,"fontSize":64,"fontWeight":"bold","align":"center","color":"black","w":490},{"type":"text","field":"name","x":16,"y":138,"fontSize":12,"fontWeight":"normal","align":"center","color":"black","w":490,"maxLines":1}]}'),
('tv_bgp_583','tpl_big_price','ESL-5.83',648,480,
'{"width":648,"height":480,"background":"white","elements":[{"type":"text","field":"price","x":24,"y":320,"fontSize":140,"fontWeight":"bold","align":"center","color":"black","w":600},{"type":"text","field":"name","x":24,"y":420,"fontSize":22,"fontWeight":"normal","align":"center","color":"black","w":600,"maxLines":1}]}'),
('tv_bgp_750','tpl_big_price','ESL-7.5',800,480,
'{"width":800,"height":480,"background":"white","elements":[{"type":"text","field":"price","x":32,"y":320,"fontSize":148,"fontWeight":"bold","align":"center","color":"black","w":736},{"type":"text","field":"name","x":32,"y":424,"fontSize":24,"fontWeight":"normal","align":"center","color":"black","w":736,"maxLines":1}]}'),
('tv_bgp_116','tpl_big_price','ESL-11.6',960,640,
'{"width":960,"height":640,"background":"white","elements":[{"type":"text","field":"price","x":40,"y":420,"fontSize":180,"fontWeight":"bold","align":"center","color":"black","w":880},{"type":"text","field":"name","x":40,"y":560,"fontSize":28,"fontWeight":"normal","align":"center","color":"black","w":880,"maxLines":1}]}');


-- ============================================================================
-- 3. PROMO / SALE — red banner + SALE badge, new price large, old price strikethrough
-- Eye catches: Red SALE badge, then new price
-- ============================================================================
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_prm_154','tpl_promo','MTAG15',152,152,
'{"width":152,"height":152,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":152,"h":32,"color":"red"},{"type":"label","text":"SALE","x":8,"y":23,"fontSize":14,"fontWeight":"bold","color":"white"},{"type":"text","field":"name","x":8,"y":56,"fontSize":12,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":136},{"type":"text","field":"old_price","x":8,"y":90,"fontSize":12,"fontWeight":"normal","align":"left","color":"black","strikethrough":true},{"type":"text","field":"price","x":8,"y":118,"fontSize":30,"fontWeight":"bold","align":"center","color":"red","w":136},{"type":"text","field":"discount","x":100,"y":23,"fontSize":11,"fontWeight":"bold","align":"right","color":"white","w":44}]}'),
('tv_prm_213','tpl_promo','ESL-2.13',250,122,
'{"width":250,"height":122,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":250,"h":28,"color":"red"},{"type":"label","text":"SALE","x":10,"y":20,"fontSize":13,"fontWeight":"bold","color":"white"},{"type":"text","field":"discount","x":180,"y":20,"fontSize":11,"fontWeight":"bold","align":"right","color":"white","w":60},{"type":"text","field":"name","x":10,"y":46,"fontSize":13,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":230},{"type":"text","field":"old_price","x":10,"y":72,"fontSize":11,"fontWeight":"normal","align":"left","color":"black","strikethrough":true},{"type":"text","field":"price","x":10,"y":104,"fontSize":28,"fontWeight":"bold","align":"center","color":"red","w":230}]}'),
('tv_prm_266','tpl_promo','DS026F',296,152,
'{"width":296,"height":152,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":296,"h":32,"color":"red"},{"type":"label","text":"SALE","x":12,"y":23,"fontSize":14,"fontWeight":"bold","color":"white"},{"type":"text","field":"discount","x":220,"y":23,"fontSize":12,"fontWeight":"bold","align":"right","color":"white","w":64},{"type":"text","field":"name","x":12,"y":52,"fontSize":14,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":272},{"type":"text","field":"old_price","x":12,"y":78,"fontSize":12,"fontWeight":"normal","align":"left","color":"black","strikethrough":true},{"type":"text","field":"price","x":12,"y":118,"fontSize":34,"fontWeight":"bold","align":"center","color":"red","w":272}]}'),
('tv_prm_267','tpl_promo','DS027Q',384,200,
'{"width":384,"height":200,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":384,"h":40,"color":"red"},{"type":"label","text":"SALE","x":16,"y":28,"fontSize":16,"fontWeight":"bold","color":"white"},{"type":"text","field":"discount","x":280,"y":28,"fontSize":14,"fontWeight":"bold","align":"right","color":"white","w":88},{"type":"text","field":"name","x":16,"y":62,"fontSize":16,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":352},{"type":"text","field":"old_price","x":16,"y":92,"fontSize":14,"fontWeight":"normal","align":"left","color":"black","strikethrough":true},{"type":"text","field":"price","x":16,"y":150,"fontSize":42,"fontWeight":"bold","align":"center","color":"red","w":352}]}'),
('tv_prm_290','tpl_promo','ESL-2.9',296,128,
'{"width":296,"height":128,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":296,"h":28,"color":"red"},{"type":"label","text":"SALE","x":12,"y":20,"fontSize":13,"fontWeight":"bold","color":"white"},{"type":"text","field":"discount","x":200,"y":20,"fontSize":11,"fontWeight":"bold","align":"right","color":"white","w":84},{"type":"text","field":"name","x":12,"y":44,"fontSize":13,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":272},{"type":"text","field":"old_price","x":12,"y":66,"fontSize":11,"fontWeight":"normal","align":"left","color":"black","strikethrough":true},{"type":"text","field":"price","x":12,"y":100,"fontSize":30,"fontWeight":"bold","align":"center","color":"red","w":272}]}'),
('tv_prm_350','tpl_promo','DS035Q',384,184,
'{"width":384,"height":184,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":384,"h":36,"color":"red"},{"type":"label","text":"SALE","x":16,"y":26,"fontSize":15,"fontWeight":"bold","color":"white"},{"type":"text","field":"discount","x":270,"y":26,"fontSize":13,"fontWeight":"bold","align":"right","color":"white","w":98},{"type":"text","field":"name","x":16,"y":58,"fontSize":15,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":352},{"type":"text","field":"old_price","x":16,"y":84,"fontSize":13,"fontWeight":"normal","align":"left","color":"black","strikethrough":true},{"type":"text","field":"price","x":16,"y":140,"fontSize":40,"fontWeight":"bold","align":"center","color":"red","w":352}]}'),
('tv_prm_420','tpl_promo','ESL-4.2',400,300,
'{"width":400,"height":300,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":400,"h":48,"color":"red"},{"type":"label","text":"SALE","x":16,"y":34,"fontSize":20,"fontWeight":"bold","color":"white"},{"type":"text","field":"discount","x":280,"y":34,"fontSize":16,"fontWeight":"bold","align":"right","color":"white","w":104},{"type":"text","field":"name","x":16,"y":76,"fontSize":18,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":368},{"type":"text","field":"old_price","x":16,"y":124,"fontSize":16,"fontWeight":"normal","align":"left","color":"black","strikethrough":true},{"type":"text","field":"price","x":16,"y":210,"fontSize":56,"fontWeight":"bold","align":"center","color":"red","w":368}]}'),
('tv_prm_430','tpl_promo','DS043Q',522,152,
'{"width":522,"height":152,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":522,"h":30,"color":"red"},{"type":"label","text":"SALE","x":16,"y":22,"fontSize":13,"fontWeight":"bold","color":"white"},{"type":"text","field":"discount","x":400,"y":22,"fontSize":11,"fontWeight":"bold","align":"right","color":"white","w":106},{"type":"text","field":"name","x":16,"y":50,"fontSize":14,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":230},{"type":"text","field":"old_price","x":276,"y":60,"fontSize":12,"fontWeight":"normal","align":"center","color":"black","w":230,"strikethrough":true},{"type":"text","field":"price","x":276,"y":100,"fontSize":42,"fontWeight":"bold","align":"center","color":"red","w":230}]}'),
('tv_prm_583','tpl_promo','ESL-5.83',648,480,
'{"width":648,"height":480,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":648,"h":64,"color":"red"},{"type":"label","text":"SALE","x":24,"y":44,"fontSize":26,"fontWeight":"bold","color":"white"},{"type":"text","field":"discount","x":460,"y":44,"fontSize":20,"fontWeight":"bold","align":"right","color":"white","w":164},{"type":"text","field":"name","x":24,"y":98,"fontSize":22,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":600},{"type":"text","field":"old_price","x":24,"y":164,"fontSize":20,"fontWeight":"normal","align":"left","color":"black","strikethrough":true},{"type":"text","field":"price","x":24,"y":300,"fontSize":72,"fontWeight":"bold","align":"center","color":"red","w":600}]}'),
('tv_prm_750','tpl_promo','ESL-7.5',800,480,
'{"width":800,"height":480,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":800,"h":64,"color":"red"},{"type":"label","text":"SALE","x":32,"y":44,"fontSize":28,"fontWeight":"bold","color":"white"},{"type":"text","field":"discount","x":560,"y":44,"fontSize":22,"fontWeight":"bold","align":"right","color":"white","w":208},{"type":"text","field":"name","x":32,"y":100,"fontSize":24,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":736},{"type":"text","field":"old_price","x":32,"y":168,"fontSize":22,"fontWeight":"normal","align":"left","color":"black","strikethrough":true},{"type":"text","field":"price","x":32,"y":300,"fontSize":80,"fontWeight":"bold","align":"center","color":"red","w":736}]}'),
('tv_prm_116','tpl_promo','ESL-11.6',960,640,
'{"width":960,"height":640,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":960,"h":80,"color":"red"},{"type":"label","text":"SALE","x":40,"y":56,"fontSize":32,"fontWeight":"bold","color":"white"},{"type":"text","field":"discount","x":660,"y":56,"fontSize":26,"fontWeight":"bold","align":"right","color":"white","w":260},{"type":"text","field":"name","x":40,"y":124,"fontSize":28,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":880},{"type":"text","field":"old_price","x":40,"y":204,"fontSize":24,"fontWeight":"normal","align":"left","color":"black","strikethrough":true},{"type":"text","field":"price","x":40,"y":390,"fontSize":96,"fontWeight":"bold","align":"center","color":"red","w":880}]}');


-- ============================================================================
-- 4. DISCOUNT FOCUS — large "-30%" center, price below, name small
-- Eye catches: Discount percentage
-- ============================================================================
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_dsc_154','tpl_discount','MTAG15',152,152,
'{"width":152,"height":152,"background":"white","elements":[{"type":"text","field":"discount","x":8,"y":76,"fontSize":42,"fontWeight":"bold","align":"center","color":"red","w":136},{"type":"line","x1":8,"y1":90,"x2":144,"y2":90,"color":"red","strokeWidth":1},{"type":"text","field":"price","x":8,"y":118,"fontSize":22,"fontWeight":"bold","align":"center","color":"black","w":136},{"type":"text","field":"name","x":8,"y":142,"fontSize":10,"fontWeight":"normal","align":"center","color":"black","w":136,"maxLines":1}]}'),
('tv_dsc_213','tpl_discount','ESL-2.13',250,122,
'{"width":250,"height":122,"background":"white","elements":[{"type":"text","field":"discount","x":10,"y":56,"fontSize":40,"fontWeight":"bold","align":"center","color":"red","w":230},{"type":"line","x1":10,"y1":68,"x2":240,"y2":68,"color":"red","strokeWidth":1},{"type":"text","field":"price","x":10,"y":96,"fontSize":22,"fontWeight":"bold","align":"center","color":"black","w":230},{"type":"text","field":"name","x":10,"y":114,"fontSize":10,"fontWeight":"normal","align":"center","color":"black","w":230,"maxLines":1}]}'),
('tv_dsc_266','tpl_discount','DS026F',296,152,
'{"width":296,"height":152,"background":"white","elements":[{"type":"text","field":"discount","x":12,"y":72,"fontSize":48,"fontWeight":"bold","align":"center","color":"red","w":272},{"type":"line","x1":12,"y1":86,"x2":284,"y2":86,"color":"red","strokeWidth":1},{"type":"text","field":"price","x":12,"y":118,"fontSize":26,"fontWeight":"bold","align":"center","color":"black","w":272},{"type":"text","field":"name","x":12,"y":142,"fontSize":11,"fontWeight":"normal","align":"center","color":"black","w":272,"maxLines":1}]}'),
('tv_dsc_267','tpl_discount','DS027Q',384,200,
'{"width":384,"height":200,"background":"white","elements":[{"type":"text","field":"discount","x":16,"y":96,"fontSize":60,"fontWeight":"bold","align":"center","color":"red","w":352},{"type":"line","x1":16,"y1":112,"x2":368,"y2":112,"color":"red","strokeWidth":1},{"type":"text","field":"price","x":16,"y":154,"fontSize":32,"fontWeight":"bold","align":"center","color":"black","w":352},{"type":"text","field":"name","x":16,"y":186,"fontSize":12,"fontWeight":"normal","align":"center","color":"black","w":352,"maxLines":1}]}'),
('tv_dsc_290','tpl_discount','ESL-2.9',296,128,
'{"width":296,"height":128,"background":"white","elements":[{"type":"text","field":"discount","x":12,"y":58,"fontSize":42,"fontWeight":"bold","align":"center","color":"red","w":272},{"type":"line","x1":12,"y1":72,"x2":284,"y2":72,"color":"red","strokeWidth":1},{"type":"text","field":"price","x":12,"y":98,"fontSize":22,"fontWeight":"bold","align":"center","color":"black","w":272},{"type":"text","field":"name","x":12,"y":118,"fontSize":10,"fontWeight":"normal","align":"center","color":"black","w":272,"maxLines":1}]}'),
('tv_dsc_350','tpl_discount','DS035Q',384,184,
'{"width":384,"height":184,"background":"white","elements":[{"type":"text","field":"discount","x":16,"y":88,"fontSize":56,"fontWeight":"bold","align":"center","color":"red","w":352},{"type":"line","x1":16,"y1":104,"x2":368,"y2":104,"color":"red","strokeWidth":1},{"type":"text","field":"price","x":16,"y":142,"fontSize":30,"fontWeight":"bold","align":"center","color":"black","w":352},{"type":"text","field":"name","x":16,"y":172,"fontSize":12,"fontWeight":"normal","align":"center","color":"black","w":352,"maxLines":1}]}'),
('tv_dsc_420','tpl_discount','ESL-4.2',400,300,
'{"width":400,"height":300,"background":"white","elements":[{"type":"text","field":"discount","x":16,"y":148,"fontSize":80,"fontWeight":"bold","align":"center","color":"red","w":368},{"type":"line","x1":16,"y1":170,"x2":384,"y2":170,"color":"red","strokeWidth":2},{"type":"text","field":"price","x":16,"y":230,"fontSize":44,"fontWeight":"bold","align":"center","color":"black","w":368},{"type":"text","field":"name","x":16,"y":276,"fontSize":16,"fontWeight":"normal","align":"center","color":"black","w":368,"maxLines":1}]}'),
('tv_dsc_430','tpl_discount','DS043Q',522,152,
'{"width":522,"height":152,"background":"white","elements":[{"type":"text","field":"discount","x":16,"y":84,"fontSize":56,"fontWeight":"bold","align":"center","color":"red","w":490},{"type":"line","x1":16,"y1":96,"x2":506,"y2":96,"color":"red","strokeWidth":1},{"type":"text","field":"price","x":16,"y":128,"fontSize":26,"fontWeight":"bold","align":"center","color":"black","w":490},{"type":"text","field":"name","x":16,"y":148,"fontSize":11,"fontWeight":"normal","align":"center","color":"black","w":490,"maxLines":1}]}'),
('tv_dsc_583','tpl_discount','ESL-5.83',648,480,
'{"width":648,"height":480,"background":"white","elements":[{"type":"text","field":"discount","x":24,"y":232,"fontSize":110,"fontWeight":"bold","align":"center","color":"red","w":600},{"type":"line","x1":24,"y1":260,"x2":624,"y2":260,"color":"red","strokeWidth":2},{"type":"text","field":"price","x":24,"y":352,"fontSize":56,"fontWeight":"bold","align":"center","color":"black","w":600},{"type":"text","field":"name","x":24,"y":420,"fontSize":20,"fontWeight":"normal","align":"center","color":"black","w":600,"maxLines":1}]}'),
('tv_dsc_750','tpl_discount','ESL-7.5',800,480,
'{"width":800,"height":480,"background":"white","elements":[{"type":"text","field":"discount","x":32,"y":232,"fontSize":120,"fontWeight":"bold","align":"center","color":"red","w":736},{"type":"line","x1":32,"y1":260,"x2":768,"y2":260,"color":"red","strokeWidth":2},{"type":"text","field":"price","x":32,"y":354,"fontSize":60,"fontWeight":"bold","align":"center","color":"black","w":736},{"type":"text","field":"name","x":32,"y":424,"fontSize":22,"fontWeight":"normal","align":"center","color":"black","w":736,"maxLines":1}]}'),
('tv_dsc_116','tpl_discount','ESL-11.6',960,640,
'{"width":960,"height":640,"background":"white","elements":[{"type":"text","field":"discount","x":40,"y":310,"fontSize":150,"fontWeight":"bold","align":"center","color":"red","w":880},{"type":"line","x1":40,"y1":340,"x2":920,"y2":340,"color":"red","strokeWidth":2},{"type":"text","field":"price","x":40,"y":460,"fontSize":72,"fontWeight":"bold","align":"center","color":"black","w":880},{"type":"text","field":"name","x":40,"y":556,"fontSize":26,"fontWeight":"normal","align":"center","color":"black","w":880,"maxLines":1}]}');


-- ============================================================================
-- 5. FRESH PRODUCE — very large name at top, clear price + unit (per kg)
-- Eye catches: Large product name, then price with unit
-- ============================================================================
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_prd_154','tpl_produce','MTAG15',152,152,
'{"width":152,"height":152,"background":"white","elements":[{"type":"text","field":"name","x":8,"y":42,"fontSize":22,"fontWeight":"bold","align":"center","color":"black","w":136,"maxLines":2},{"type":"line","x1":8,"y1":68,"x2":144,"y2":68,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":8,"y":108,"fontSize":28,"fontWeight":"bold","align":"center","color":"black","w":136},{"type":"text","field":"unit","x":8,"y":138,"fontSize":12,"fontWeight":"bold","align":"center","color":"red","w":136}]}'),
('tv_prd_213','tpl_produce','ESL-2.13',250,122,
'{"width":250,"height":122,"background":"white","elements":[{"type":"text","field":"name","x":10,"y":30,"fontSize":20,"fontWeight":"bold","align":"center","color":"black","w":230,"maxLines":1},{"type":"line","x1":10,"y1":44,"x2":240,"y2":44,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":10,"y":84,"fontSize":28,"fontWeight":"bold","align":"center","color":"black","w":150},{"type":"text","field":"unit","x":170,"y":84,"fontSize":13,"fontWeight":"bold","align":"left","color":"red","w":70}]}'),
('tv_prd_266','tpl_produce','DS026F',296,152,
'{"width":296,"height":152,"background":"white","elements":[{"type":"text","field":"name","x":12,"y":34,"fontSize":22,"fontWeight":"bold","align":"center","color":"black","w":272,"maxLines":1},{"type":"line","x1":12,"y1":50,"x2":284,"y2":50,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":12,"y":104,"fontSize":36,"fontWeight":"bold","align":"center","color":"black","w":190},{"type":"text","field":"unit","x":210,"y":104,"fontSize":14,"fontWeight":"bold","align":"left","color":"red","w":74}]}'),
('tv_prd_267','tpl_produce','DS027Q',384,200,
'{"width":384,"height":200,"background":"white","elements":[{"type":"text","field":"name","x":16,"y":42,"fontSize":26,"fontWeight":"bold","align":"center","color":"black","w":352,"maxLines":1},{"type":"line","x1":16,"y1":62,"x2":368,"y2":62,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":16,"y":132,"fontSize":44,"fontWeight":"bold","align":"center","color":"black","w":240},{"type":"text","field":"unit","x":264,"y":132,"fontSize":16,"fontWeight":"bold","align":"left","color":"red","w":104}]}'),
('tv_prd_290','tpl_produce','ESL-2.9',296,128,
'{"width":296,"height":128,"background":"white","elements":[{"type":"text","field":"name","x":12,"y":28,"fontSize":18,"fontWeight":"bold","align":"center","color":"black","w":272,"maxLines":1},{"type":"line","x1":12,"y1":42,"x2":284,"y2":42,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":12,"y":84,"fontSize":30,"fontWeight":"bold","align":"center","color":"black","w":190},{"type":"text","field":"unit","x":210,"y":84,"fontSize":12,"fontWeight":"bold","align":"left","color":"red","w":74}]}'),
('tv_prd_350','tpl_produce','DS035Q',384,184,
'{"width":384,"height":184,"background":"white","elements":[{"type":"text","field":"name","x":16,"y":38,"fontSize":24,"fontWeight":"bold","align":"center","color":"black","w":352,"maxLines":1},{"type":"line","x1":16,"y1":56,"x2":368,"y2":56,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":16,"y":120,"fontSize":42,"fontWeight":"bold","align":"center","color":"black","w":240},{"type":"text","field":"unit","x":264,"y":120,"fontSize":15,"fontWeight":"bold","align":"left","color":"red","w":104}]}'),
('tv_prd_420','tpl_produce','ESL-4.2',400,300,
'{"width":400,"height":300,"background":"white","elements":[{"type":"text","field":"name","x":16,"y":56,"fontSize":30,"fontWeight":"bold","align":"center","color":"black","w":368,"maxLines":2},{"type":"line","x1":16,"y1":84,"x2":384,"y2":84,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":16,"y":194,"fontSize":60,"fontWeight":"bold","align":"center","color":"black","w":260},{"type":"text","field":"unit","x":284,"y":194,"fontSize":18,"fontWeight":"bold","align":"left","color":"red","w":100}]}'),
('tv_prd_430','tpl_produce','DS043Q',522,152,
'{"width":522,"height":152,"background":"white","elements":[{"type":"text","field":"name","x":16,"y":34,"fontSize":22,"fontWeight":"bold","align":"left","color":"black","w":230,"maxLines":2},{"type":"line","x1":260,"y1":12,"x2":260,"y2":140,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":276,"y":84,"fontSize":40,"fontWeight":"bold","align":"center","color":"black","w":160},{"type":"text","field":"unit","x":440,"y":84,"fontSize":14,"fontWeight":"bold","align":"left","color":"red","w":66}]}'),
('tv_prd_583','tpl_produce','ESL-5.83',648,480,
'{"width":648,"height":480,"background":"white","elements":[{"type":"text","field":"name","x":24,"y":72,"fontSize":38,"fontWeight":"bold","align":"center","color":"black","w":600,"maxLines":2},{"type":"line","x1":24,"y1":112,"x2":624,"y2":112,"color":"black","strokeWidth":2},{"type":"text","field":"price","x":24,"y":296,"fontSize":80,"fontWeight":"bold","align":"center","color":"black","w":420},{"type":"text","field":"unit","x":452,"y":296,"fontSize":24,"fontWeight":"bold","align":"left","color":"red","w":172}]}'),
('tv_prd_750','tpl_produce','ESL-7.5',800,480,
'{"width":800,"height":480,"background":"white","elements":[{"type":"text","field":"name","x":32,"y":68,"fontSize":38,"fontWeight":"bold","align":"center","color":"black","w":736,"maxLines":2},{"type":"line","x1":32,"y1":108,"x2":768,"y2":108,"color":"black","strokeWidth":2},{"type":"text","field":"price","x":32,"y":296,"fontSize":84,"fontWeight":"bold","align":"center","color":"black","w":520},{"type":"text","field":"unit","x":560,"y":296,"fontSize":26,"fontWeight":"bold","align":"left","color":"red","w":208}]}'),
('tv_prd_116','tpl_produce','ESL-11.6',960,640,
'{"width":960,"height":640,"background":"white","elements":[{"type":"text","field":"name","x":40,"y":88,"fontSize":48,"fontWeight":"bold","align":"center","color":"black","w":880,"maxLines":2},{"type":"line","x1":40,"y1":140,"x2":920,"y2":140,"color":"black","strokeWidth":2},{"type":"text","field":"price","x":40,"y":394,"fontSize":100,"fontWeight":"bold","align":"center","color":"black","w":620},{"type":"text","field":"unit","x":670,"y":394,"fontSize":30,"fontWeight":"bold","align":"left","color":"red","w":250}]}');


-- ============================================================================
-- 6. MINIMAL — name + price only, massive whitespace, centered
-- Eye catches: Whitespace / atmosphere, then price
-- ============================================================================
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_mnl_154','tpl_minimal','MTAG15',152,152,
'{"width":152,"height":152,"background":"white","elements":[{"type":"text","field":"name","x":8,"y":52,"fontSize":12,"fontWeight":"normal","align":"center","color":"black","maxLines":1,"w":136},{"type":"text","field":"price","x":8,"y":102,"fontSize":32,"fontWeight":"bold","align":"center","color":"black","w":136}]}'),
('tv_mnl_213','tpl_minimal','ESL-2.13',250,122,
'{"width":250,"height":122,"background":"white","elements":[{"type":"text","field":"name","x":10,"y":38,"fontSize":12,"fontWeight":"normal","align":"center","color":"black","maxLines":1,"w":230},{"type":"text","field":"price","x":10,"y":84,"fontSize":32,"fontWeight":"bold","align":"center","color":"black","w":230}]}'),
('tv_mnl_266','tpl_minimal','DS026F',296,152,
'{"width":296,"height":152,"background":"white","elements":[{"type":"text","field":"name","x":12,"y":48,"fontSize":13,"fontWeight":"normal","align":"center","color":"black","maxLines":1,"w":272},{"type":"text","field":"price","x":12,"y":102,"fontSize":38,"fontWeight":"bold","align":"center","color":"black","w":272}]}'),
('tv_mnl_267','tpl_minimal','DS027Q',384,200,
'{"width":384,"height":200,"background":"white","elements":[{"type":"text","field":"name","x":16,"y":60,"fontSize":14,"fontWeight":"normal","align":"center","color":"black","maxLines":1,"w":352},{"type":"text","field":"price","x":16,"y":132,"fontSize":46,"fontWeight":"bold","align":"center","color":"black","w":352}]}'),
('tv_mnl_290','tpl_minimal','ESL-2.9',296,128,
'{"width":296,"height":128,"background":"white","elements":[{"type":"text","field":"name","x":12,"y":38,"fontSize":12,"fontWeight":"normal","align":"center","color":"black","maxLines":1,"w":272},{"type":"text","field":"price","x":12,"y":84,"fontSize":32,"fontWeight":"bold","align":"center","color":"black","w":272}]}'),
('tv_mnl_350','tpl_minimal','DS035Q',384,184,
'{"width":384,"height":184,"background":"white","elements":[{"type":"text","field":"name","x":16,"y":56,"fontSize":13,"fontWeight":"normal","align":"center","color":"black","maxLines":1,"w":352},{"type":"text","field":"price","x":16,"y":124,"fontSize":42,"fontWeight":"bold","align":"center","color":"black","w":352}]}'),
('tv_mnl_420','tpl_minimal','ESL-4.2',400,300,
'{"width":400,"height":300,"background":"white","elements":[{"type":"text","field":"name","x":16,"y":90,"fontSize":17,"fontWeight":"normal","align":"center","color":"black","maxLines":1,"w":368},{"type":"text","field":"price","x":16,"y":192,"fontSize":60,"fontWeight":"bold","align":"center","color":"black","w":368}]}'),
('tv_mnl_430','tpl_minimal','DS043Q',522,152,
'{"width":522,"height":152,"background":"white","elements":[{"type":"text","field":"name","x":16,"y":50,"fontSize":14,"fontWeight":"normal","align":"center","color":"black","maxLines":1,"w":490},{"type":"text","field":"price","x":16,"y":104,"fontSize":40,"fontWeight":"bold","align":"center","color":"black","w":490}]}'),
('tv_mnl_583','tpl_minimal','ESL-5.83',648,480,
'{"width":648,"height":480,"background":"white","elements":[{"type":"text","field":"name","x":24,"y":148,"fontSize":22,"fontWeight":"normal","align":"center","color":"black","maxLines":1,"w":600},{"type":"text","field":"price","x":24,"y":300,"fontSize":72,"fontWeight":"bold","align":"center","color":"black","w":600}]}'),
('tv_mnl_750','tpl_minimal','ESL-7.5',800,480,
'{"width":800,"height":480,"background":"white","elements":[{"type":"text","field":"name","x":32,"y":140,"fontSize":24,"fontWeight":"normal","align":"center","color":"black","maxLines":1,"w":736},{"type":"text","field":"price","x":32,"y":300,"fontSize":80,"fontWeight":"bold","align":"center","color":"black","w":736}]}'),
('tv_mnl_116','tpl_minimal','ESL-11.6',960,640,
'{"width":960,"height":640,"background":"white","elements":[{"type":"text","field":"name","x":40,"y":190,"fontSize":28,"fontWeight":"normal","align":"center","color":"black","maxLines":1,"w":880},{"type":"text","field":"price","x":40,"y":400,"fontSize":96,"fontWeight":"bold","align":"center","color":"black","w":880}]}');


-- ============================================================================
-- 7. INFO CARD — category / name / description / price (information-dense)
-- Eye catches: Name and description, then price
-- ============================================================================
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_nfo_154','tpl_info','MTAG15',152,152,
'{"width":152,"height":152,"background":"white","elements":[{"type":"text","field":"category","x":8,"y":14,"fontSize":8,"fontWeight":"normal","align":"left","color":"red"},{"type":"text","field":"name","x":8,"y":32,"fontSize":13,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":136},{"type":"line","x1":8,"y1":56,"x2":144,"y2":56,"color":"black","strokeWidth":1},{"type":"text","field":"description","x":8,"y":76,"fontSize":9,"fontWeight":"normal","align":"left","color":"black","maxLines":3,"w":136},{"type":"text","field":"price","x":8,"y":130,"fontSize":20,"fontWeight":"bold","align":"right","color":"black","w":136}]}'),
('tv_nfo_213','tpl_info','ESL-2.13',250,122,
'{"width":250,"height":122,"background":"white","elements":[{"type":"text","field":"category","x":10,"y":13,"fontSize":8,"fontWeight":"normal","align":"left","color":"red"},{"type":"text","field":"name","x":10,"y":28,"fontSize":14,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":230},{"type":"line","x1":10,"y1":38,"x2":240,"y2":38,"color":"black","strokeWidth":1},{"type":"text","field":"description","x":10,"y":56,"fontSize":9,"fontWeight":"normal","align":"left","color":"black","maxLines":2,"w":230},{"type":"text","field":"price","x":10,"y":100,"fontSize":22,"fontWeight":"bold","align":"right","color":"black","w":230}]}'),
('tv_nfo_266','tpl_info','DS026F',296,152,
'{"width":296,"height":152,"background":"white","elements":[{"type":"text","field":"category","x":12,"y":14,"fontSize":9,"fontWeight":"normal","align":"left","color":"red"},{"type":"text","field":"name","x":12,"y":32,"fontSize":15,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":272},{"type":"line","x1":12,"y1":44,"x2":284,"y2":44,"color":"black","strokeWidth":1},{"type":"text","field":"description","x":12,"y":64,"fontSize":10,"fontWeight":"normal","align":"left","color":"black","maxLines":3,"w":272},{"type":"text","field":"price","x":12,"y":126,"fontSize":24,"fontWeight":"bold","align":"right","color":"black","w":272}]}'),
('tv_nfo_267','tpl_info','DS027Q',384,200,
'{"width":384,"height":200,"background":"white","elements":[{"type":"text","field":"category","x":16,"y":16,"fontSize":10,"fontWeight":"normal","align":"left","color":"red"},{"type":"text","field":"name","x":16,"y":36,"fontSize":17,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":352},{"type":"line","x1":16,"y1":50,"x2":368,"y2":50,"color":"black","strokeWidth":1},{"type":"text","field":"description","x":16,"y":72,"fontSize":11,"fontWeight":"normal","align":"left","color":"black","maxLines":3,"w":352},{"type":"text","field":"price","x":16,"y":164,"fontSize":30,"fontWeight":"bold","align":"right","color":"black","w":352}]}'),
('tv_nfo_290','tpl_info','ESL-2.9',296,128,
'{"width":296,"height":128,"background":"white","elements":[{"type":"text","field":"category","x":12,"y":13,"fontSize":8,"fontWeight":"normal","align":"left","color":"red"},{"type":"text","field":"name","x":12,"y":28,"fontSize":14,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":272},{"type":"line","x1":12,"y1":38,"x2":284,"y2":38,"color":"black","strokeWidth":1},{"type":"text","field":"description","x":12,"y":56,"fontSize":9,"fontWeight":"normal","align":"left","color":"black","maxLines":2,"w":272},{"type":"text","field":"price","x":12,"y":100,"fontSize":22,"fontWeight":"bold","align":"right","color":"black","w":272}]}'),
('tv_nfo_350','tpl_info','DS035Q',384,184,
'{"width":384,"height":184,"background":"white","elements":[{"type":"text","field":"category","x":16,"y":15,"fontSize":9,"fontWeight":"normal","align":"left","color":"red"},{"type":"text","field":"name","x":16,"y":34,"fontSize":16,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":352},{"type":"line","x1":16,"y1":48,"x2":368,"y2":48,"color":"black","strokeWidth":1},{"type":"text","field":"description","x":16,"y":68,"fontSize":10,"fontWeight":"normal","align":"left","color":"black","maxLines":3,"w":352},{"type":"text","field":"price","x":16,"y":150,"fontSize":28,"fontWeight":"bold","align":"right","color":"black","w":352}]}'),
('tv_nfo_420','tpl_info','ESL-4.2',400,300,
'{"width":400,"height":300,"background":"white","elements":[{"type":"text","field":"category","x":16,"y":22,"fontSize":11,"fontWeight":"normal","align":"left","color":"red"},{"type":"text","field":"name","x":16,"y":46,"fontSize":20,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":368},{"type":"line","x1":16,"y1":78,"x2":384,"y2":78,"color":"black","strokeWidth":1},{"type":"text","field":"description","x":16,"y":104,"fontSize":13,"fontWeight":"normal","align":"left","color":"black","maxLines":4,"w":368},{"type":"text","field":"price","x":16,"y":244,"fontSize":42,"fontWeight":"bold","align":"right","color":"black","w":368}]}'),
('tv_nfo_430','tpl_info','DS043Q',522,152,
'{"width":522,"height":152,"background":"white","elements":[{"type":"text","field":"category","x":16,"y":14,"fontSize":9,"fontWeight":"normal","align":"left","color":"red"},{"type":"text","field":"name","x":16,"y":32,"fontSize":15,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":240},{"type":"text","field":"description","x":16,"y":80,"fontSize":9,"fontWeight":"normal","align":"left","color":"black","maxLines":3,"w":240},{"type":"line","x1":270,"y1":12,"x2":270,"y2":140,"color":"black","strokeWidth":1},{"type":"text","field":"price","x":286,"y":86,"fontSize":40,"fontWeight":"bold","align":"center","color":"black","w":220}]}'),
('tv_nfo_583','tpl_info','ESL-5.83',648,480,
'{"width":648,"height":480,"background":"white","elements":[{"type":"text","field":"category","x":24,"y":28,"fontSize":14,"fontWeight":"normal","align":"left","color":"red"},{"type":"text","field":"name","x":24,"y":58,"fontSize":24,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":600},{"type":"line","x1":24,"y1":100,"x2":624,"y2":100,"color":"black","strokeWidth":1},{"type":"text","field":"description","x":24,"y":132,"fontSize":16,"fontWeight":"normal","align":"left","color":"black","maxLines":5,"w":600},{"type":"text","field":"price","x":24,"y":368,"fontSize":60,"fontWeight":"bold","align":"right","color":"black","w":600}]}'),
('tv_nfo_750','tpl_info','ESL-7.5',800,480,
'{"width":800,"height":480,"background":"white","elements":[{"type":"text","field":"category","x":32,"y":28,"fontSize":15,"fontWeight":"normal","align":"left","color":"red"},{"type":"text","field":"name","x":32,"y":58,"fontSize":26,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":736},{"type":"line","x1":32,"y1":100,"x2":768,"y2":100,"color":"black","strokeWidth":1},{"type":"text","field":"description","x":32,"y":132,"fontSize":16,"fontWeight":"normal","align":"left","color":"black","maxLines":5,"w":736},{"type":"text","field":"price","x":32,"y":370,"fontSize":64,"fontWeight":"bold","align":"right","color":"black","w":736}]}'),
('tv_nfo_116','tpl_info','ESL-11.6',960,640,
'{"width":960,"height":640,"background":"white","elements":[{"type":"text","field":"category","x":40,"y":36,"fontSize":18,"fontWeight":"normal","align":"left","color":"red"},{"type":"text","field":"name","x":40,"y":72,"fontSize":32,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":880},{"type":"line","x1":40,"y1":128,"x2":920,"y2":128,"color":"black","strokeWidth":2},{"type":"text","field":"description","x":40,"y":168,"fontSize":20,"fontWeight":"normal","align":"left","color":"black","maxLines":6,"w":880},{"type":"text","field":"price","x":40,"y":490,"fontSize":80,"fontWeight":"bold","align":"right","color":"black","w":880}]}');


-- ============================================================================
-- 8. UNIT PRICE FOCUS — unit price dominant (red), regular price small, name small
-- Eye catches: Unit price (per kg/unit)
-- ============================================================================
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_upr_154','tpl_unit_price','MTAG15',152,152,
'{"width":152,"height":152,"background":"white","elements":[{"type":"text","field":"name","x":8,"y":18,"fontSize":11,"fontWeight":"normal","align":"left","color":"black","maxLines":1,"w":136},{"type":"line","x1":8,"y1":28,"x2":144,"y2":28,"color":"black","strokeWidth":1},{"type":"text","field":"unit","x":8,"y":48,"fontSize":10,"fontWeight":"bold","align":"center","color":"red","w":136},{"type":"text","field":"price","x":8,"y":96,"fontSize":36,"fontWeight":"bold","align":"center","color":"red","w":136},{"type":"line","x1":8,"y1":112,"x2":144,"y2":112,"color":"black","strokeWidth":1},{"type":"label","text":"total:","x":8,"y":132,"fontSize":9,"fontWeight":"normal","color":"black"},{"type":"text","field":"price","x":52,"y":132,"fontSize":14,"fontWeight":"bold","align":"left","color":"black"}]}'),
('tv_upr_213','tpl_unit_price','ESL-2.13',250,122,
'{"width":250,"height":122,"background":"white","elements":[{"type":"text","field":"name","x":10,"y":16,"fontSize":11,"fontWeight":"normal","align":"left","color":"black","maxLines":1,"w":230},{"type":"line","x1":10,"y1":24,"x2":240,"y2":24,"color":"black","strokeWidth":1},{"type":"text","field":"unit","x":10,"y":42,"fontSize":10,"fontWeight":"bold","align":"center","color":"red","w":230},{"type":"text","field":"price","x":10,"y":82,"fontSize":32,"fontWeight":"bold","align":"center","color":"red","w":230},{"type":"line","x1":10,"y1":94,"x2":240,"y2":94,"color":"black","strokeWidth":1},{"type":"label","text":"total:","x":10,"y":112,"fontSize":9,"fontWeight":"normal","color":"black"},{"type":"text","field":"price","x":52,"y":112,"fontSize":13,"fontWeight":"bold","align":"left","color":"black"}]}'),
('tv_upr_266','tpl_unit_price','DS026F',296,152,
'{"width":296,"height":152,"background":"white","elements":[{"type":"text","field":"name","x":12,"y":18,"fontSize":12,"fontWeight":"normal","align":"left","color":"black","maxLines":1,"w":272},{"type":"line","x1":12,"y1":28,"x2":284,"y2":28,"color":"black","strokeWidth":1},{"type":"text","field":"unit","x":12,"y":48,"fontSize":11,"fontWeight":"bold","align":"center","color":"red","w":272},{"type":"text","field":"price","x":12,"y":100,"fontSize":38,"fontWeight":"bold","align":"center","color":"red","w":272},{"type":"line","x1":12,"y1":114,"x2":284,"y2":114,"color":"black","strokeWidth":1},{"type":"label","text":"total:","x":12,"y":136,"fontSize":10,"fontWeight":"normal","color":"black"},{"type":"text","field":"price","x":60,"y":136,"fontSize":16,"fontWeight":"bold","align":"left","color":"black"}]}'),
('tv_upr_267','tpl_unit_price','DS027Q',384,200,
'{"width":384,"height":200,"background":"white","elements":[{"type":"text","field":"name","x":16,"y":20,"fontSize":13,"fontWeight":"normal","align":"left","color":"black","maxLines":1,"w":352},{"type":"line","x1":16,"y1":30,"x2":368,"y2":30,"color":"black","strokeWidth":1},{"type":"text","field":"unit","x":16,"y":52,"fontSize":12,"fontWeight":"bold","align":"center","color":"red","w":352},{"type":"text","field":"price","x":16,"y":122,"fontSize":48,"fontWeight":"bold","align":"center","color":"red","w":352},{"type":"line","x1":16,"y1":140,"x2":368,"y2":140,"color":"black","strokeWidth":1},{"type":"label","text":"total:","x":16,"y":168,"fontSize":11,"fontWeight":"normal","color":"black"},{"type":"text","field":"price","x":68,"y":168,"fontSize":20,"fontWeight":"bold","align":"left","color":"black"}]}'),
('tv_upr_290','tpl_unit_price','ESL-2.9',296,128,
'{"width":296,"height":128,"background":"white","elements":[{"type":"text","field":"name","x":12,"y":16,"fontSize":11,"fontWeight":"normal","align":"left","color":"black","maxLines":1,"w":272},{"type":"line","x1":12,"y1":24,"x2":284,"y2":24,"color":"black","strokeWidth":1},{"type":"text","field":"unit","x":12,"y":40,"fontSize":10,"fontWeight":"bold","align":"center","color":"red","w":272},{"type":"text","field":"price","x":12,"y":80,"fontSize":32,"fontWeight":"bold","align":"center","color":"red","w":272},{"type":"line","x1":12,"y1":94,"x2":284,"y2":94,"color":"black","strokeWidth":1},{"type":"label","text":"total:","x":12,"y":112,"fontSize":9,"fontWeight":"normal","color":"black"},{"type":"text","field":"price","x":52,"y":112,"fontSize":13,"fontWeight":"bold","align":"left","color":"black"}]}'),
('tv_upr_350','tpl_unit_price','DS035Q',384,184,
'{"width":384,"height":184,"background":"white","elements":[{"type":"text","field":"name","x":16,"y":20,"fontSize":12,"fontWeight":"normal","align":"left","color":"black","maxLines":1,"w":352},{"type":"line","x1":16,"y1":30,"x2":368,"y2":30,"color":"black","strokeWidth":1},{"type":"text","field":"unit","x":16,"y":50,"fontSize":11,"fontWeight":"bold","align":"center","color":"red","w":352},{"type":"text","field":"price","x":16,"y":114,"fontSize":44,"fontWeight":"bold","align":"center","color":"red","w":352},{"type":"line","x1":16,"y1":130,"x2":368,"y2":130,"color":"black","strokeWidth":1},{"type":"label","text":"total:","x":16,"y":158,"fontSize":10,"fontWeight":"normal","color":"black"},{"type":"text","field":"price","x":64,"y":158,"fontSize":18,"fontWeight":"bold","align":"left","color":"black"}]}'),
('tv_upr_420','tpl_unit_price','ESL-4.2',400,300,
'{"width":400,"height":300,"background":"white","elements":[{"type":"text","field":"name","x":16,"y":28,"fontSize":15,"fontWeight":"normal","align":"left","color":"black","maxLines":1,"w":368},{"type":"line","x1":16,"y1":40,"x2":384,"y2":40,"color":"black","strokeWidth":1},{"type":"text","field":"unit","x":16,"y":66,"fontSize":14,"fontWeight":"bold","align":"center","color":"red","w":368},{"type":"text","field":"price","x":16,"y":178,"fontSize":64,"fontWeight":"bold","align":"center","color":"red","w":368},{"type":"line","x1":16,"y1":200,"x2":384,"y2":200,"color":"black","strokeWidth":1},{"type":"label","text":"total:","x":16,"y":242,"fontSize":13,"fontWeight":"normal","color":"black"},{"type":"text","field":"price","x":76,"y":242,"fontSize":28,"fontWeight":"bold","align":"left","color":"black"}]}'),
('tv_upr_430','tpl_unit_price','DS043Q',522,152,
'{"width":522,"height":152,"background":"white","elements":[{"type":"text","field":"name","x":16,"y":20,"fontSize":12,"fontWeight":"normal","align":"left","color":"black","maxLines":1,"w":240},{"type":"line","x1":270,"y1":12,"x2":270,"y2":140,"color":"black","strokeWidth":1},{"type":"text","field":"unit","x":286,"y":36,"fontSize":11,"fontWeight":"bold","align":"center","color":"red","w":220},{"type":"text","field":"price","x":286,"y":86,"fontSize":40,"fontWeight":"bold","align":"center","color":"red","w":220},{"type":"line","x1":286,"y1":102,"x2":506,"y2":102,"color":"black","strokeWidth":1},{"type":"label","text":"total:","x":286,"y":126,"fontSize":10,"fontWeight":"normal","color":"black"},{"type":"text","field":"price","x":336,"y":126,"fontSize":16,"fontWeight":"bold","align":"left","color":"black"}]}'),
('tv_upr_583','tpl_unit_price','ESL-5.83',648,480,
'{"width":648,"height":480,"background":"white","elements":[{"type":"text","field":"name","x":24,"y":36,"fontSize":20,"fontWeight":"normal","align":"left","color":"black","maxLines":1,"w":600},{"type":"line","x1":24,"y1":52,"x2":624,"y2":52,"color":"black","strokeWidth":1},{"type":"text","field":"unit","x":24,"y":82,"fontSize":18,"fontWeight":"bold","align":"center","color":"red","w":600},{"type":"text","field":"price","x":24,"y":272,"fontSize":84,"fontWeight":"bold","align":"center","color":"red","w":600},{"type":"line","x1":24,"y1":300,"x2":624,"y2":300,"color":"black","strokeWidth":2},{"type":"label","text":"total:","x":24,"y":360,"fontSize":16,"fontWeight":"normal","color":"black"},{"type":"text","field":"price","x":100,"y":360,"fontSize":36,"fontWeight":"bold","align":"left","color":"black"}]}'),
('tv_upr_750','tpl_unit_price','ESL-7.5',800,480,
'{"width":800,"height":480,"background":"white","elements":[{"type":"text","field":"name","x":32,"y":36,"fontSize":22,"fontWeight":"normal","align":"left","color":"black","maxLines":1,"w":736},{"type":"line","x1":32,"y1":52,"x2":768,"y2":52,"color":"black","strokeWidth":1},{"type":"text","field":"unit","x":32,"y":82,"fontSize":20,"fontWeight":"bold","align":"center","color":"red","w":736},{"type":"text","field":"price","x":32,"y":280,"fontSize":90,"fontWeight":"bold","align":"center","color":"red","w":736},{"type":"line","x1":32,"y1":306,"x2":768,"y2":306,"color":"black","strokeWidth":2},{"type":"label","text":"total:","x":32,"y":370,"fontSize":18,"fontWeight":"normal","color":"black"},{"type":"text","field":"price","x":112,"y":370,"fontSize":40,"fontWeight":"bold","align":"left","color":"black"}]}'),
('tv_upr_116','tpl_unit_price','ESL-11.6',960,640,
'{"width":960,"height":640,"background":"white","elements":[{"type":"text","field":"name","x":40,"y":44,"fontSize":26,"fontWeight":"normal","align":"left","color":"black","maxLines":1,"w":880},{"type":"line","x1":40,"y1":64,"x2":920,"y2":64,"color":"black","strokeWidth":2},{"type":"text","field":"unit","x":40,"y":100,"fontSize":24,"fontWeight":"bold","align":"center","color":"red","w":880},{"type":"text","field":"price","x":40,"y":370,"fontSize":110,"fontWeight":"bold","align":"center","color":"red","w":880},{"type":"line","x1":40,"y1":400,"x2":920,"y2":400,"color":"black","strokeWidth":2},{"type":"label","text":"total:","x":40,"y":480,"fontSize":22,"fontWeight":"normal","color":"black"},{"type":"text","field":"price","x":140,"y":480,"fontSize":50,"fontWeight":"bold","align":"left","color":"black"}]}');


-- ============================================================================
-- 9. STATUS TAG — full-screen badge (red bg or yellow bg), status text centered
-- Eye catches: Status badge fills entire screen
-- ============================================================================
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_sts_154','tpl_status','MTAG15',152,152,
'{"width":152,"height":152,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":152,"h":152,"color":"red"},{"type":"text","field":"badge_text","x":8,"y":86,"fontSize":20,"fontWeight":"bold","align":"center","color":"white","w":136,"maxLines":2},{"type":"text","field":"name","x":8,"y":130,"fontSize":10,"fontWeight":"normal","align":"center","color":"white","w":136,"maxLines":1}]}'),
('tv_sts_213','tpl_status','ESL-2.13',250,122,
'{"width":250,"height":122,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":250,"h":122,"color":"red"},{"type":"text","field":"badge_text","x":10,"y":62,"fontSize":22,"fontWeight":"bold","align":"center","color":"white","w":230,"maxLines":2},{"type":"text","field":"name","x":10,"y":104,"fontSize":10,"fontWeight":"normal","align":"center","color":"white","w":230,"maxLines":1}]}'),
('tv_sts_266','tpl_status','DS026F',296,152,
'{"width":296,"height":152,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":296,"h":152,"color":"red"},{"type":"text","field":"badge_text","x":12,"y":78,"fontSize":26,"fontWeight":"bold","align":"center","color":"white","w":272,"maxLines":2},{"type":"text","field":"name","x":12,"y":130,"fontSize":11,"fontWeight":"normal","align":"center","color":"white","w":272,"maxLines":1}]}'),
('tv_sts_267','tpl_status','DS027Q',384,200,
'{"width":384,"height":200,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":384,"h":200,"color":"red"},{"type":"text","field":"badge_text","x":16,"y":100,"fontSize":32,"fontWeight":"bold","align":"center","color":"white","w":352,"maxLines":2},{"type":"text","field":"name","x":16,"y":168,"fontSize":13,"fontWeight":"normal","align":"center","color":"white","w":352,"maxLines":1}]}'),
('tv_sts_290','tpl_status','ESL-2.9',296,128,
'{"width":296,"height":128,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":296,"h":128,"color":"red"},{"type":"text","field":"badge_text","x":12,"y":62,"fontSize":24,"fontWeight":"bold","align":"center","color":"white","w":272,"maxLines":2},{"type":"text","field":"name","x":12,"y":108,"fontSize":10,"fontWeight":"normal","align":"center","color":"white","w":272,"maxLines":1}]}'),
('tv_sts_350','tpl_status','DS035Q',384,184,
'{"width":384,"height":184,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":384,"h":184,"color":"red"},{"type":"text","field":"badge_text","x":16,"y":92,"fontSize":30,"fontWeight":"bold","align":"center","color":"white","w":352,"maxLines":2},{"type":"text","field":"name","x":16,"y":152,"fontSize":12,"fontWeight":"normal","align":"center","color":"white","w":352,"maxLines":1}]}'),
('tv_sts_420','tpl_status','ESL-4.2',400,300,
'{"width":400,"height":300,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":400,"h":300,"color":"red"},{"type":"text","field":"badge_text","x":16,"y":150,"fontSize":42,"fontWeight":"bold","align":"center","color":"white","w":368,"maxLines":2},{"type":"text","field":"name","x":16,"y":244,"fontSize":16,"fontWeight":"normal","align":"center","color":"white","w":368,"maxLines":1}]}'),
('tv_sts_430','tpl_status','DS043Q',522,152,
'{"width":522,"height":152,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":522,"h":152,"color":"red"},{"type":"text","field":"badge_text","x":16,"y":80,"fontSize":32,"fontWeight":"bold","align":"center","color":"white","w":490,"maxLines":2},{"type":"text","field":"name","x":16,"y":132,"fontSize":12,"fontWeight":"normal","align":"center","color":"white","w":490,"maxLines":1}]}'),
('tv_sts_583','tpl_status','ESL-5.83',648,480,
'{"width":648,"height":480,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":648,"h":480,"color":"red"},{"type":"text","field":"badge_text","x":24,"y":240,"fontSize":56,"fontWeight":"bold","align":"center","color":"white","w":600,"maxLines":2},{"type":"text","field":"name","x":24,"y":384,"fontSize":22,"fontWeight":"normal","align":"center","color":"white","w":600,"maxLines":1}]}'),
('tv_sts_750','tpl_status','ESL-7.5',800,480,
'{"width":800,"height":480,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":800,"h":480,"color":"red"},{"type":"text","field":"badge_text","x":32,"y":240,"fontSize":60,"fontWeight":"bold","align":"center","color":"white","w":736,"maxLines":2},{"type":"text","field":"name","x":32,"y":388,"fontSize":24,"fontWeight":"normal","align":"center","color":"white","w":736,"maxLines":1}]}'),
('tv_sts_116','tpl_status','ESL-11.6',960,640,
'{"width":960,"height":640,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":960,"h":640,"color":"red"},{"type":"text","field":"badge_text","x":40,"y":316,"fontSize":76,"fontWeight":"bold","align":"center","color":"white","w":880,"maxLines":2},{"type":"text","field":"name","x":40,"y":510,"fontSize":28,"fontWeight":"normal","align":"center","color":"white","w":880,"maxLines":1}]}');


-- ============================================================================
-- 10. IMAGE + PRICE — image left ~40%, name + price right ~60%
-- Eye catches: Product image, then price
-- ============================================================================
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_img_154','tpl_image_price','MTAG15',152,152,
'{"width":152,"height":152,"background":"white","elements":[{"type":"image","field":"imageUrl","x":4,"y":4,"w":64,"h":64},{"type":"text","field":"name","x":4,"y":86,"fontSize":12,"fontWeight":"bold","align":"center","color":"black","maxLines":2,"w":144},{"type":"text","field":"price","x":4,"y":132,"fontSize":26,"fontWeight":"bold","align":"center","color":"black","w":144}]}'),
('tv_img_213','tpl_image_price','ESL-2.13',250,122,
'{"width":250,"height":122,"background":"white","elements":[{"type":"image","field":"imageUrl","x":8,"y":8,"w":90,"h":106},{"type":"text","field":"name","x":110,"y":24,"fontSize":13,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":130},{"type":"text","field":"price","x":110,"y":86,"fontSize":26,"fontWeight":"bold","align":"left","color":"black","w":130}]}'),
('tv_img_266','tpl_image_price','DS026F',296,152,
'{"width":296,"height":152,"background":"white","elements":[{"type":"image","field":"imageUrl","x":8,"y":8,"w":110,"h":136},{"type":"text","field":"name","x":130,"y":26,"fontSize":14,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":154},{"type":"text","field":"price","x":130,"y":104,"fontSize":30,"fontWeight":"bold","align":"left","color":"black","w":154}]}'),
('tv_img_267','tpl_image_price','DS027Q',384,200,
'{"width":384,"height":200,"background":"white","elements":[{"type":"image","field":"imageUrl","x":12,"y":12,"w":140,"h":176},{"type":"text","field":"name","x":168,"y":30,"fontSize":16,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":200},{"type":"text","field":"price","x":168,"y":132,"fontSize":38,"fontWeight":"bold","align":"left","color":"black","w":200}]}'),
('tv_img_290','tpl_image_price','ESL-2.9',296,128,
'{"width":296,"height":128,"background":"white","elements":[{"type":"image","field":"imageUrl","x":8,"y":8,"w":100,"h":112},{"type":"text","field":"name","x":120,"y":24,"fontSize":13,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":164},{"type":"text","field":"price","x":120,"y":84,"fontSize":28,"fontWeight":"bold","align":"left","color":"black","w":164}]}'),
('tv_img_350','tpl_image_price','DS035Q',384,184,
'{"width":384,"height":184,"background":"white","elements":[{"type":"image","field":"imageUrl","x":12,"y":12,"w":130,"h":160},{"type":"text","field":"name","x":158,"y":28,"fontSize":15,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":210},{"type":"text","field":"price","x":158,"y":120,"fontSize":36,"fontWeight":"bold","align":"left","color":"black","w":210}]}'),
('tv_img_420','tpl_image_price','ESL-4.2',400,300,
'{"width":400,"height":300,"background":"white","elements":[{"type":"image","field":"imageUrl","x":12,"y":12,"w":160,"h":276},{"type":"text","field":"name","x":188,"y":36,"fontSize":18,"fontWeight":"bold","align":"left","color":"black","maxLines":3,"w":196},{"type":"text","field":"price","x":188,"y":200,"fontSize":46,"fontWeight":"bold","align":"left","color":"black","w":196}]}'),
('tv_img_430','tpl_image_price','DS043Q',522,152,
'{"width":522,"height":152,"background":"white","elements":[{"type":"image","field":"imageUrl","x":8,"y":8,"w":130,"h":136},{"type":"text","field":"name","x":152,"y":26,"fontSize":15,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":354},{"type":"text","field":"price","x":152,"y":100,"fontSize":34,"fontWeight":"bold","align":"left","color":"black","w":354}]}'),
('tv_img_583','tpl_image_price','ESL-5.83',648,480,
'{"width":648,"height":480,"background":"white","elements":[{"type":"image","field":"imageUrl","x":16,"y":16,"w":240,"h":448},{"type":"text","field":"name","x":280,"y":48,"fontSize":24,"fontWeight":"bold","align":"left","color":"black","maxLines":3,"w":344},{"type":"text","field":"price","x":280,"y":300,"fontSize":60,"fontWeight":"bold","align":"left","color":"black","w":344}]}'),
('tv_img_750','tpl_image_price','ESL-7.5',800,480,
'{"width":800,"height":480,"background":"white","elements":[{"type":"image","field":"imageUrl","x":20,"y":20,"w":300,"h":440},{"type":"text","field":"name","x":344,"y":48,"fontSize":26,"fontWeight":"bold","align":"left","color":"black","maxLines":3,"w":424},{"type":"text","field":"price","x":344,"y":300,"fontSize":64,"fontWeight":"bold","align":"left","color":"black","w":424}]}'),
('tv_img_116','tpl_image_price','ESL-11.6',960,640,
'{"width":960,"height":640,"background":"white","elements":[{"type":"image","field":"imageUrl","x":24,"y":24,"w":360,"h":592},{"type":"text","field":"name","x":412,"y":60,"fontSize":32,"fontWeight":"bold","align":"left","color":"black","maxLines":3,"w":516},{"type":"text","field":"price","x":412,"y":400,"fontSize":80,"fontWeight":"bold","align":"left","color":"black","w":516}]}');
