-- ============================================================================
-- LUXURY PROMO — Black bg, yellow pill accent, red SALE badge, image, details
-- Dramatic dark layout with golden accent ellipse behind the price
-- Eye catches: Yellow pill shape, then SALE badge, then price
-- ============================================================================

INSERT OR IGNORE INTO templates (id, name, description, kind, created_at, purpose, when_to_use) VALUES
  ('tpl_luxury_promo', 'Luxury Promo', 'Dramatic dark background with golden accent shape, red SALE badge, strikethrough old price, large new price, product image, and detail specs.', 'promo', '2025-01-01T00:00:00Z', 'High-impact promotional display for premium products', 'Use for flagship promotions where maximum visual drama is needed — black background with golden accents and red SALE badge.');

-- MTAG15 — 152×152
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_lxp_154','tpl_luxury_promo','MTAG15',152,152,
'{"width":152,"height":152,"background":"black","elements":[{"type":"rect","x":-20,"y":50,"w":100,"h":80,"color":"yellow","radius":40},{"type":"rect","x":0,"y":0,"w":152,"h":28,"color":"red","radius":0},{"type":"badge","text":"SALE","x":4,"y":4,"w":52,"h":20,"fontSize":11,"fontWeight":"bold","color":"white","bgColor":"red","radius":10,"paddingX":8,"paddingY":3},{"type":"text","field":"name","x":8,"y":48,"fontSize":11,"fontWeight":"bold","align":"left","color":"white","maxLines":1,"w":136},{"type":"text","field":"old_price","x":8,"y":68,"fontSize":10,"fontWeight":"normal","align":"left","color":"white","strikethrough":true},{"type":"text","field":"price","x":8,"y":104,"fontSize":30,"fontWeight":"bold","align":"center","color":"white","w":136},{"type":"line","x1":8,"y1":116,"x2":144,"y2":116,"color":"yellow","strokeWidth":1},{"type":"text","field":"detail1","x":8,"y":132,"fontSize":7,"fontWeight":"normal","align":"left","color":"yellow","w":136,"maxLines":1},{"type":"text","field":"detail2","x":8,"y":143,"fontSize":7,"fontWeight":"normal","align":"left","color":"yellow","w":136,"maxLines":1}]}');

-- ESL-2.13 — 250×122
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_lxp_213','tpl_luxury_promo','ESL-2.13',250,122,
'{"width":250,"height":122,"background":"black","elements":[{"type":"rect","x":-30,"y":30,"w":140,"h":90,"color":"yellow","radius":45},{"type":"rect","x":0,"y":0,"w":250,"h":26,"color":"red","radius":0},{"type":"badge","text":"SALE","x":6,"y":3,"w":56,"h":20,"fontSize":11,"fontWeight":"bold","color":"white","bgColor":"red","radius":10,"paddingX":8,"paddingY":3},{"type":"text","field":"discount","x":150,"y":18,"fontSize":10,"fontWeight":"bold","align":"right","color":"white","w":94},{"type":"text","field":"name","x":10,"y":44,"fontSize":12,"fontWeight":"bold","align":"left","color":"white","maxLines":1,"w":230},{"type":"text","field":"old_price","x":10,"y":62,"fontSize":10,"fontWeight":"normal","align":"left","color":"white","strikethrough":true},{"type":"text","field":"price","x":10,"y":94,"fontSize":28,"fontWeight":"bold","align":"center","color":"white","w":230},{"type":"line","x1":10,"y1":102,"x2":240,"y2":102,"color":"yellow","strokeWidth":1},{"type":"text","field":"detail1","x":10,"y":114,"fontSize":7,"fontWeight":"normal","align":"left","color":"yellow","w":110,"maxLines":1},{"type":"text","field":"detail2","x":130,"y":114,"fontSize":7,"fontWeight":"normal","align":"left","color":"yellow","w":110,"maxLines":1}]}');

-- DS026F — 296×152
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_lxp_266','tpl_luxury_promo','DS026F',296,152,
'{"width":296,"height":152,"background":"black","elements":[{"type":"rect","x":-40,"y":35,"w":170,"h":110,"color":"yellow","radius":55},{"type":"rect","x":0,"y":0,"w":296,"h":28,"color":"red","radius":0},{"type":"badge","text":"SALE","x":8,"y":4,"w":60,"h":20,"fontSize":11,"fontWeight":"bold","color":"white","bgColor":"red","radius":10,"paddingX":10,"paddingY":3},{"type":"text","field":"discount","x":180,"y":18,"fontSize":11,"fontWeight":"bold","align":"right","color":"white","w":108},{"type":"text","field":"name","x":12,"y":48,"fontSize":14,"fontWeight":"bold","align":"left","color":"white","maxLines":1,"w":272},{"type":"text","field":"old_price","x":12,"y":68,"fontSize":11,"fontWeight":"normal","align":"left","color":"white","strikethrough":true},{"type":"text","field":"price","x":12,"y":106,"fontSize":32,"fontWeight":"bold","align":"center","color":"white","w":272},{"type":"line","x1":12,"y1":118,"x2":284,"y2":118,"color":"yellow","strokeWidth":1},{"type":"text","field":"detail1","x":12,"y":132,"fontSize":8,"fontWeight":"normal","align":"left","color":"yellow","w":130,"maxLines":1},{"type":"text","field":"detail2","x":154,"y":132,"fontSize":8,"fontWeight":"normal","align":"left","color":"yellow","w":130,"maxLines":1},{"type":"text","field":"detail3","x":12,"y":144,"fontSize":8,"fontWeight":"normal","align":"left","color":"yellow","w":272,"maxLines":1}]}');

-- DS027Q — 384×200
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_lxp_267','tpl_luxury_promo','DS027Q',384,200,
'{"width":384,"height":200,"background":"black","elements":[{"type":"rect","x":-50,"y":40,"w":220,"h":150,"color":"yellow","radius":70},{"type":"rect","x":0,"y":0,"w":384,"h":34,"color":"red","radius":0},{"type":"badge","text":"SALE","x":10,"y":5,"w":68,"h":24,"fontSize":13,"fontWeight":"bold","color":"white","bgColor":"red","radius":12,"paddingX":10,"paddingY":4},{"type":"text","field":"discount","x":240,"y":22,"fontSize":12,"fontWeight":"bold","align":"right","color":"white","w":134},{"type":"text","field":"name","x":16,"y":58,"fontSize":16,"fontWeight":"bold","align":"left","color":"white","maxLines":1,"w":352},{"type":"text","field":"old_price","x":16,"y":80,"fontSize":13,"fontWeight":"normal","align":"left","color":"white","strikethrough":true},{"type":"text","field":"price","x":16,"y":130,"fontSize":40,"fontWeight":"bold","align":"center","color":"white","w":352},{"type":"line","x1":16,"y1":146,"x2":368,"y2":146,"color":"yellow","strokeWidth":2},{"type":"image","field":"imageUrl","x":288,"y":52,"w":80,"h":80},{"type":"text","field":"detail1","x":16,"y":164,"fontSize":9,"fontWeight":"normal","align":"left","color":"yellow","w":170,"maxLines":1},{"type":"text","field":"detail2","x":16,"y":178,"fontSize":9,"fontWeight":"normal","align":"left","color":"yellow","w":170,"maxLines":1},{"type":"text","field":"detail3","x":200,"y":164,"fontSize":9,"fontWeight":"normal","align":"left","color":"yellow","w":170,"maxLines":1}]}');

-- ESL-2.9 — 296×128
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_lxp_290','tpl_luxury_promo','ESL-2.9',296,128,
'{"width":296,"height":128,"background":"black","elements":[{"type":"rect","x":-36,"y":30,"w":160,"h":96,"color":"yellow","radius":48},{"type":"rect","x":0,"y":0,"w":296,"h":26,"color":"red","radius":0},{"type":"badge","text":"SALE","x":8,"y":3,"w":56,"h":20,"fontSize":11,"fontWeight":"bold","color":"white","bgColor":"red","radius":10,"paddingX":8,"paddingY":3},{"type":"text","field":"discount","x":180,"y":18,"fontSize":10,"fontWeight":"bold","align":"right","color":"white","w":108},{"type":"text","field":"name","x":12,"y":44,"fontSize":13,"fontWeight":"bold","align":"left","color":"white","maxLines":1,"w":272},{"type":"text","field":"old_price","x":12,"y":62,"fontSize":10,"fontWeight":"normal","align":"left","color":"white","strikethrough":true},{"type":"text","field":"price","x":12,"y":94,"fontSize":28,"fontWeight":"bold","align":"center","color":"white","w":272},{"type":"line","x1":12,"y1":104,"x2":284,"y2":104,"color":"yellow","strokeWidth":1},{"type":"text","field":"detail1","x":12,"y":118,"fontSize":7,"fontWeight":"normal","align":"left","color":"yellow","w":130,"maxLines":1},{"type":"text","field":"detail2","x":154,"y":118,"fontSize":7,"fontWeight":"normal","align":"left","color":"yellow","w":130,"maxLines":1}]}');

-- DS035Q — 384×184
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_lxp_350','tpl_luxury_promo','DS035Q',384,184,
'{"width":384,"height":184,"background":"black","elements":[{"type":"rect","x":-45,"y":36,"w":200,"h":140,"color":"yellow","radius":65},{"type":"rect","x":0,"y":0,"w":384,"h":30,"color":"red","radius":0},{"type":"badge","text":"SALE","x":10,"y":5,"w":64,"h":22,"fontSize":12,"fontWeight":"bold","color":"white","bgColor":"red","radius":11,"paddingX":10,"paddingY":4},{"type":"text","field":"discount","x":230,"y":20,"fontSize":11,"fontWeight":"bold","align":"right","color":"white","w":144},{"type":"text","field":"name","x":16,"y":52,"fontSize":15,"fontWeight":"bold","align":"left","color":"white","maxLines":1,"w":352},{"type":"text","field":"old_price","x":16,"y":72,"fontSize":12,"fontWeight":"normal","align":"left","color":"white","strikethrough":true},{"type":"text","field":"price","x":16,"y":118,"fontSize":36,"fontWeight":"bold","align":"center","color":"white","w":352},{"type":"line","x1":16,"y1":132,"x2":368,"y2":132,"color":"yellow","strokeWidth":2},{"type":"image","field":"imageUrl","x":296,"y":42,"w":72,"h":72},{"type":"text","field":"detail1","x":16,"y":148,"fontSize":8,"fontWeight":"normal","align":"left","color":"yellow","w":170,"maxLines":1},{"type":"text","field":"detail2","x":16,"y":162,"fontSize":8,"fontWeight":"normal","align":"left","color":"yellow","w":170,"maxLines":1},{"type":"text","field":"detail3","x":200,"y":148,"fontSize":8,"fontWeight":"normal","align":"left","color":"yellow","w":170,"maxLines":1}]}');

-- ESL-4.2 — 400×300
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_lxp_420','tpl_luxury_promo','ESL-4.2',400,300,
'{"width":400,"height":300,"background":"black","elements":[{"type":"rect","x":-60,"y":60,"w":280,"h":220,"color":"yellow","radius":100},{"type":"rect","x":0,"y":0,"w":400,"h":42,"color":"red","radius":0},{"type":"badge","text":"SALE","x":12,"y":8,"w":76,"h":26,"fontSize":14,"fontWeight":"bold","color":"white","bgColor":"red","radius":13,"paddingX":12,"paddingY":4},{"type":"text","field":"discount","x":260,"y":28,"fontSize":14,"fontWeight":"bold","align":"right","color":"white","w":130},{"type":"text","field":"name","x":16,"y":70,"fontSize":18,"fontWeight":"bold","align":"left","color":"white","maxLines":2,"w":240},{"type":"text","field":"old_price","x":16,"y":108,"fontSize":14,"fontWeight":"normal","align":"left","color":"white","strikethrough":true},{"type":"text","field":"price","x":16,"y":170,"fontSize":52,"fontWeight":"bold","align":"center","color":"white","w":368},{"type":"line","x1":16,"y1":192,"x2":384,"y2":192,"color":"yellow","strokeWidth":2},{"type":"image","field":"imageUrl","x":280,"y":60,"w":104,"h":104},{"type":"text","field":"detail1","x":16,"y":216,"fontSize":10,"fontWeight":"normal","align":"left","color":"yellow","w":180,"maxLines":1},{"type":"text","field":"detail2","x":16,"y":234,"fontSize":10,"fontWeight":"normal","align":"left","color":"yellow","w":180,"maxLines":1},{"type":"text","field":"detail3","x":16,"y":252,"fontSize":10,"fontWeight":"normal","align":"left","color":"yellow","w":180,"maxLines":1},{"type":"text","field":"unit","x":16,"y":278,"fontSize":10,"fontWeight":"bold","align":"left","color":"yellow","w":180}]}');

-- DS043Q — 522×152
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_lxp_430','tpl_luxury_promo','DS043Q',522,152,
'{"width":522,"height":152,"background":"black","elements":[{"type":"rect","x":-40,"y":24,"w":200,"h":120,"color":"yellow","radius":60},{"type":"rect","x":0,"y":0,"w":522,"h":26,"color":"red","radius":0},{"type":"badge","text":"SALE","x":8,"y":3,"w":56,"h":20,"fontSize":11,"fontWeight":"bold","color":"white","bgColor":"red","radius":10,"paddingX":8,"paddingY":3},{"type":"text","field":"discount","x":370,"y":18,"fontSize":10,"fontWeight":"bold","align":"right","color":"white","w":144},{"type":"text","field":"name","x":16,"y":46,"fontSize":14,"fontWeight":"bold","align":"left","color":"white","maxLines":1,"w":260},{"type":"text","field":"old_price","x":16,"y":66,"fontSize":10,"fontWeight":"normal","align":"left","color":"white","strikethrough":true},{"type":"text","field":"price","x":16,"y":100,"fontSize":30,"fontWeight":"bold","align":"left","color":"white","w":200},{"type":"line","x1":290,"y1":34,"x2":290,"y2":144,"color":"yellow","strokeWidth":2},{"type":"image","field":"imageUrl","x":306,"y":34,"w":86,"h":86},{"type":"text","field":"detail1","x":406,"y":50,"fontSize":8,"fontWeight":"normal","align":"left","color":"yellow","w":108,"maxLines":1},{"type":"text","field":"detail2","x":406,"y":64,"fontSize":8,"fontWeight":"normal","align":"left","color":"yellow","w":108,"maxLines":1},{"type":"text","field":"detail3","x":406,"y":78,"fontSize":8,"fontWeight":"normal","align":"left","color":"yellow","w":108,"maxLines":1},{"type":"line","x1":16,"y1":114,"x2":274,"y2":114,"color":"yellow","strokeWidth":1},{"type":"text","field":"unit","x":16,"y":132,"fontSize":9,"fontWeight":"bold","align":"left","color":"yellow","w":260}]}');

-- ESL-5.83 — 648×480
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_lxp_583','tpl_luxury_promo','ESL-5.83',648,480,
'{"width":648,"height":480,"background":"black","elements":[{"type":"rect","x":-80,"y":80,"w":380,"h":360,"color":"yellow","radius":160},{"type":"rect","x":0,"y":0,"w":648,"h":56,"color":"red","radius":0},{"type":"badge","text":"SALE","x":16,"y":10,"w":90,"h":34,"fontSize":18,"fontWeight":"bold","color":"white","bgColor":"red","radius":17,"paddingX":14,"paddingY":6},{"type":"text","field":"discount","x":420,"y":36,"fontSize":18,"fontWeight":"bold","align":"right","color":"white","w":212},{"type":"text","field":"name","x":24,"y":90,"fontSize":24,"fontWeight":"bold","align":"left","color":"white","maxLines":2,"w":370},{"type":"text","field":"old_price","x":24,"y":140,"fontSize":18,"fontWeight":"normal","align":"left","color":"white","strikethrough":true},{"type":"text","field":"price","x":24,"y":240,"fontSize":72,"fontWeight":"bold","align":"center","color":"white","w":600},{"type":"line","x1":24,"y1":264,"x2":624,"y2":264,"color":"yellow","strokeWidth":3},{"type":"image","field":"imageUrl","x":420,"y":80,"w":200,"h":160},{"type":"rect","x":24,"y":290,"w":280,"h":3,"color":"yellow","radius":2},{"type":"text","field":"detail1","x":24,"y":316,"fontSize":13,"fontWeight":"normal","align":"left","color":"yellow","w":290,"maxLines":1},{"type":"text","field":"detail2","x":24,"y":340,"fontSize":13,"fontWeight":"normal","align":"left","color":"yellow","w":290,"maxLines":1},{"type":"text","field":"detail3","x":24,"y":364,"fontSize":13,"fontWeight":"normal","align":"left","color":"yellow","w":290,"maxLines":1},{"type":"text","field":"unit","x":24,"y":400,"fontSize":13,"fontWeight":"bold","align":"left","color":"yellow","w":290},{"type":"text","field":"category","x":24,"y":448,"fontSize":11,"fontWeight":"normal","align":"left","color":"white","w":290}]}');

-- ESL-7.5 — 800×480
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_lxp_750','tpl_luxury_promo','ESL-7.5',800,480,
'{"width":800,"height":480,"background":"black","elements":[{"type":"rect","x":-90,"y":70,"w":440,"h":380,"color":"yellow","radius":180},{"type":"rect","x":0,"y":0,"w":800,"h":56,"color":"red","radius":0},{"type":"badge","text":"SALE","x":20,"y":10,"w":96,"h":36,"fontSize":19,"fontWeight":"bold","color":"white","bgColor":"red","radius":18,"paddingX":16,"paddingY":6},{"type":"text","field":"discount","x":540,"y":38,"fontSize":20,"fontWeight":"bold","align":"right","color":"white","w":240},{"type":"text","field":"name","x":32,"y":92,"fontSize":26,"fontWeight":"bold","align":"left","color":"white","maxLines":2,"w":440},{"type":"text","field":"old_price","x":32,"y":146,"fontSize":20,"fontWeight":"normal","align":"left","color":"white","strikethrough":true},{"type":"text","field":"price","x":32,"y":250,"fontSize":80,"fontWeight":"bold","align":"center","color":"white","w":736},{"type":"line","x1":32,"y1":276,"x2":768,"y2":276,"color":"yellow","strokeWidth":3},{"type":"image","field":"imageUrl","x":520,"y":80,"w":248,"h":180},{"type":"text","field":"detail1","x":32,"y":306,"fontSize":14,"fontWeight":"normal","align":"left","color":"yellow","w":460,"maxLines":1},{"type":"text","field":"detail2","x":32,"y":330,"fontSize":14,"fontWeight":"normal","align":"left","color":"yellow","w":460,"maxLines":1},{"type":"text","field":"detail3","x":32,"y":354,"fontSize":14,"fontWeight":"normal","align":"left","color":"yellow","w":460,"maxLines":1},{"type":"text","field":"unit","x":32,"y":392,"fontSize":14,"fontWeight":"bold","align":"left","color":"yellow","w":460},{"type":"text","field":"category","x":32,"y":448,"fontSize":12,"fontWeight":"normal","align":"left","color":"white","w":460}]}');

-- ESL-11.6 — 960×640
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_lxp_116','tpl_luxury_promo','ESL-11.6',960,640,
'{"width":960,"height":640,"background":"black","elements":[{"type":"rect","x":-100,"y":80,"w":520,"h":520,"color":"yellow","radius":240},{"type":"rect","x":0,"y":0,"w":960,"h":68,"color":"red","radius":0},{"type":"badge","text":"SALE","x":24,"y":12,"w":110,"h":42,"fontSize":22,"fontWeight":"bold","color":"white","bgColor":"red","radius":21,"paddingX":18,"paddingY":8},{"type":"text","field":"discount","x":640,"y":46,"fontSize":24,"fontWeight":"bold","align":"right","color":"white","w":296},{"type":"text","field":"name","x":40,"y":112,"fontSize":32,"fontWeight":"bold","align":"left","color":"white","maxLines":2,"w":540},{"type":"text","field":"old_price","x":40,"y":180,"fontSize":24,"fontWeight":"normal","align":"left","color":"white","strikethrough":true},{"type":"text","field":"price","x":40,"y":316,"fontSize":100,"fontWeight":"bold","align":"center","color":"white","w":880},{"type":"line","x1":40,"y1":348,"x2":920,"y2":348,"color":"yellow","strokeWidth":3},{"type":"image","field":"imageUrl","x":620,"y":100,"w":300,"h":230},{"type":"text","field":"detail1","x":40,"y":386,"fontSize":17,"fontWeight":"normal","align":"left","color":"yellow","w":540,"maxLines":1},{"type":"text","field":"detail2","x":40,"y":416,"fontSize":17,"fontWeight":"normal","align":"left","color":"yellow","w":540,"maxLines":1},{"type":"text","field":"detail3","x":40,"y":446,"fontSize":17,"fontWeight":"normal","align":"left","color":"yellow","w":540,"maxLines":1},{"type":"text","field":"unit","x":40,"y":494,"fontSize":16,"fontWeight":"bold","align":"left","color":"yellow","w":540},{"type":"text","field":"category","x":40,"y":580,"fontSize":15,"fontWeight":"normal","align":"left","color":"white","w":540}]}');


-- ============================================================================
-- ============================================================================
-- ELITE DISPLAY — Red/white split, layered rounded shapes, maximum impact
-- White bg with bold red accent shapes creating depth and drama
-- Eye catches: Stacked red shapes, then price, then badge + details
-- ============================================================================
-- ============================================================================

INSERT OR IGNORE INTO templates (id, name, description, kind, created_at, purpose, when_to_use) VALUES
  ('tpl_elite_display', 'Elite Display', 'Split red/white design with layered rounded accent shapes, pill badge, image area, and stacked detail lines — maximum shelf presence.', 'showcase', '2025-01-01T00:00:00Z', 'Premium shelf display with architectural visual design', 'Use for hero products or special editions that need a striking, modern label — layered shapes create depth and premium feel.');

-- MTAG15 — 152×152
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_elt_154','tpl_elite_display','MTAG15',152,152,
'{"width":152,"height":152,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":152,"h":42,"color":"red","radius":0},{"type":"rect","x":90,"y":28,"w":58,"h":58,"color":"red","radius":29},{"type":"badge","field":"discount","x":6,"y":6,"w":60,"h":18,"fontSize":9,"fontWeight":"bold","color":"white","bgColor":"black","radius":9,"paddingX":6,"paddingY":3},{"type":"text","field":"name","x":8,"y":58,"fontSize":12,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":78},{"type":"text","field":"price","x":8,"y":108,"fontSize":30,"fontWeight":"bold","align":"left","color":"red","w":90},{"type":"line","x1":8,"y1":118,"x2":144,"y2":118,"color":"red","strokeWidth":1},{"type":"text","field":"detail1","x":8,"y":132,"fontSize":7,"fontWeight":"normal","align":"left","color":"black","w":136,"maxLines":1},{"type":"text","field":"detail2","x":8,"y":143,"fontSize":7,"fontWeight":"normal","align":"left","color":"black","w":136,"maxLines":1}]}');

-- ESL-2.13 — 250×122
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_elt_213','tpl_elite_display','ESL-2.13',250,122,
'{"width":250,"height":122,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":250,"h":38,"color":"red","radius":0},{"type":"rect","x":170,"y":22,"w":70,"h":70,"color":"red","radius":35},{"type":"badge","field":"discount","x":8,"y":6,"w":80,"h":20,"fontSize":10,"fontWeight":"bold","color":"white","bgColor":"black","radius":10,"paddingX":8,"paddingY":3},{"type":"text","field":"name","x":10,"y":58,"fontSize":13,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":154},{"type":"text","field":"old_price","x":10,"y":76,"fontSize":9,"fontWeight":"normal","align":"left","color":"black","strikethrough":true},{"type":"text","field":"price","x":10,"y":102,"fontSize":24,"fontWeight":"bold","align":"left","color":"red","w":140},{"type":"line","x1":10,"y1":108,"x2":160,"y2":108,"color":"red","strokeWidth":1},{"type":"text","field":"detail1","x":10,"y":118,"fontSize":7,"fontWeight":"normal","align":"left","color":"black","w":115,"maxLines":1},{"type":"text","field":"detail2","x":130,"y":118,"fontSize":7,"fontWeight":"normal","align":"left","color":"black","w":115,"maxLines":1}]}');

-- DS026F — 296×152
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_elt_266','tpl_elite_display','DS026F',296,152,
'{"width":296,"height":152,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":296,"h":42,"color":"red","radius":0},{"type":"rect","x":210,"y":26,"w":76,"h":76,"color":"red","radius":38},{"type":"badge","field":"discount","x":10,"y":8,"w":90,"h":22,"fontSize":11,"fontWeight":"bold","color":"white","bgColor":"black","radius":11,"paddingX":8,"paddingY":4},{"type":"text","field":"name","x":12,"y":64,"fontSize":14,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":190},{"type":"text","field":"old_price","x":12,"y":82,"fontSize":10,"fontWeight":"normal","align":"left","color":"black","strikethrough":true},{"type":"text","field":"price","x":12,"y":116,"fontSize":30,"fontWeight":"bold","align":"left","color":"red","w":170},{"type":"line","x1":12,"y1":126,"x2":200,"y2":126,"color":"red","strokeWidth":1},{"type":"text","field":"detail1","x":12,"y":138,"fontSize":8,"fontWeight":"normal","align":"left","color":"black","w":130,"maxLines":1},{"type":"text","field":"detail2","x":154,"y":138,"fontSize":8,"fontWeight":"normal","align":"left","color":"black","w":130,"maxLines":1}]}');

-- DS027Q — 384×200
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_elt_267','tpl_elite_display','DS027Q',384,200,
'{"width":384,"height":200,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":384,"h":50,"color":"red","radius":0},{"type":"rect","x":280,"y":30,"w":90,"h":90,"color":"red","radius":45},{"type":"rect","x":290,"y":40,"w":70,"h":70,"color":"yellow","radius":35},{"type":"badge","field":"discount","x":12,"y":10,"w":110,"h":26,"fontSize":13,"fontWeight":"bold","color":"white","bgColor":"black","radius":13,"paddingX":10,"paddingY":4},{"type":"text","field":"name","x":16,"y":76,"fontSize":16,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":258},{"type":"text","field":"old_price","x":16,"y":96,"fontSize":12,"fontWeight":"normal","align":"left","color":"black","strikethrough":true},{"type":"text","field":"price","x":16,"y":142,"fontSize":38,"fontWeight":"bold","align":"left","color":"red","w":220},{"type":"line","x1":16,"y1":154,"x2":260,"y2":154,"color":"red","strokeWidth":2},{"type":"text","field":"detail1","x":16,"y":170,"fontSize":9,"fontWeight":"normal","align":"left","color":"black","w":170,"maxLines":1},{"type":"text","field":"detail2","x":16,"y":184,"fontSize":9,"fontWeight":"normal","align":"left","color":"black","w":170,"maxLines":1},{"type":"text","field":"detail3","x":200,"y":170,"fontSize":9,"fontWeight":"normal","align":"left","color":"black","w":170,"maxLines":1}]}');

-- ESL-2.9 — 296×128
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_elt_290','tpl_elite_display','ESL-2.9',296,128,
'{"width":296,"height":128,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":296,"h":36,"color":"red","radius":0},{"type":"rect","x":216,"y":20,"w":70,"h":70,"color":"red","radius":35},{"type":"badge","field":"discount","x":8,"y":6,"w":84,"h":20,"fontSize":10,"fontWeight":"bold","color":"white","bgColor":"black","radius":10,"paddingX":8,"paddingY":3},{"type":"text","field":"name","x":12,"y":54,"fontSize":13,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":198},{"type":"text","field":"old_price","x":12,"y":70,"fontSize":9,"fontWeight":"normal","align":"left","color":"black","strikethrough":true},{"type":"text","field":"price","x":12,"y":96,"fontSize":24,"fontWeight":"bold","align":"left","color":"red","w":150},{"type":"line","x1":12,"y1":104,"x2":200,"y2":104,"color":"red","strokeWidth":1},{"type":"text","field":"detail1","x":12,"y":116,"fontSize":7,"fontWeight":"normal","align":"left","color":"black","w":130,"maxLines":1},{"type":"text","field":"detail2","x":154,"y":116,"fontSize":7,"fontWeight":"normal","align":"left","color":"black","w":130,"maxLines":1}]}');

-- DS035Q — 384×184
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_elt_350','tpl_elite_display','DS035Q',384,184,
'{"width":384,"height":184,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":384,"h":46,"color":"red","radius":0},{"type":"rect","x":280,"y":28,"w":86,"h":86,"color":"red","radius":43},{"type":"rect","x":290,"y":38,"w":66,"h":66,"color":"yellow","radius":33},{"type":"badge","field":"discount","x":12,"y":8,"w":100,"h":24,"fontSize":12,"fontWeight":"bold","color":"white","bgColor":"black","radius":12,"paddingX":10,"paddingY":4},{"type":"text","field":"name","x":16,"y":70,"fontSize":15,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":258},{"type":"text","field":"old_price","x":16,"y":88,"fontSize":11,"fontWeight":"normal","align":"left","color":"black","strikethrough":true},{"type":"text","field":"price","x":16,"y":130,"fontSize":34,"fontWeight":"bold","align":"left","color":"red","w":220},{"type":"line","x1":16,"y1":142,"x2":260,"y2":142,"color":"red","strokeWidth":2},{"type":"text","field":"detail1","x":16,"y":158,"fontSize":8,"fontWeight":"normal","align":"left","color":"black","w":170,"maxLines":1},{"type":"text","field":"detail2","x":16,"y":172,"fontSize":8,"fontWeight":"normal","align":"left","color":"black","w":170,"maxLines":1},{"type":"text","field":"detail3","x":200,"y":158,"fontSize":8,"fontWeight":"normal","align":"left","color":"black","w":170,"maxLines":1}]}');

-- ESL-4.2 — 400×300
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_elt_420','tpl_elite_display','ESL-4.2',400,300,
'{"width":400,"height":300,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":400,"h":60,"color":"red","radius":0},{"type":"rect","x":280,"y":34,"w":110,"h":110,"color":"red","radius":55},{"type":"rect","x":294,"y":48,"w":82,"h":82,"color":"yellow","radius":41},{"type":"badge","field":"discount","x":14,"y":12,"w":120,"h":30,"fontSize":14,"fontWeight":"bold","color":"white","bgColor":"black","radius":15,"paddingX":12,"paddingY":5},{"type":"text","field":"name","x":16,"y":88,"fontSize":18,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":258},{"type":"text","field":"old_price","x":16,"y":124,"fontSize":14,"fontWeight":"normal","align":"left","color":"black","strikethrough":true},{"type":"text","field":"price","x":16,"y":182,"fontSize":48,"fontWeight":"bold","align":"left","color":"red","w":260},{"type":"line","x1":16,"y1":198,"x2":270,"y2":198,"color":"red","strokeWidth":2},{"type":"image","field":"imageUrl","x":280,"y":156,"w":104,"h":104},{"type":"text","field":"detail1","x":16,"y":220,"fontSize":10,"fontWeight":"normal","align":"left","color":"black","w":250,"maxLines":1},{"type":"text","field":"detail2","x":16,"y":238,"fontSize":10,"fontWeight":"normal","align":"left","color":"black","w":250,"maxLines":1},{"type":"text","field":"detail3","x":16,"y":256,"fontSize":10,"fontWeight":"normal","align":"left","color":"black","w":250,"maxLines":1},{"type":"text","field":"unit","x":16,"y":280,"fontSize":10,"fontWeight":"bold","align":"left","color":"red","w":250}]}');

-- DS043Q — 522×152
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_elt_430','tpl_elite_display','DS043Q',522,152,
'{"width":522,"height":152,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":522,"h":36,"color":"red","radius":0},{"type":"rect","x":430,"y":18,"w":76,"h":76,"color":"red","radius":38},{"type":"rect","x":440,"y":28,"w":56,"h":56,"color":"yellow","radius":28},{"type":"badge","field":"discount","x":10,"y":6,"w":90,"h":22,"fontSize":11,"fontWeight":"bold","color":"white","bgColor":"black","radius":11,"paddingX":8,"paddingY":4},{"type":"text","field":"name","x":16,"y":58,"fontSize":14,"fontWeight":"bold","align":"left","color":"black","maxLines":1,"w":280},{"type":"text","field":"old_price","x":16,"y":76,"fontSize":10,"fontWeight":"normal","align":"left","color":"black","strikethrough":true},{"type":"text","field":"price","x":16,"y":108,"fontSize":30,"fontWeight":"bold","align":"left","color":"red","w":200},{"type":"line","x1":310,"y1":44,"x2":310,"y2":144,"color":"red","strokeWidth":2},{"type":"image","field":"imageUrl","x":326,"y":44,"w":86,"h":86},{"type":"line","x1":16,"y1":120,"x2":296,"y2":120,"color":"red","strokeWidth":1},{"type":"text","field":"detail1","x":16,"y":134,"fontSize":8,"fontWeight":"normal","align":"left","color":"black","w":140,"maxLines":1},{"type":"text","field":"detail2","x":164,"y":134,"fontSize":8,"fontWeight":"normal","align":"left","color":"black","w":140,"maxLines":1}]}');

-- ESL-5.83 — 648×480
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_elt_583','tpl_elite_display','ESL-5.83',648,480,
'{"width":648,"height":480,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":648,"h":76,"color":"red","radius":0},{"type":"rect","x":440,"y":44,"w":160,"h":160,"color":"red","radius":80},{"type":"rect","x":460,"y":64,"w":120,"h":120,"color":"yellow","radius":60},{"type":"badge","field":"discount","x":18,"y":16,"w":140,"h":36,"fontSize":17,"fontWeight":"bold","color":"white","bgColor":"black","radius":18,"paddingX":14,"paddingY":6},{"type":"text","field":"name","x":24,"y":112,"fontSize":24,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":400},{"type":"text","field":"old_price","x":24,"y":158,"fontSize":18,"fontWeight":"normal","align":"left","color":"black","strikethrough":true},{"type":"text","field":"price","x":24,"y":260,"fontSize":68,"fontWeight":"bold","align":"left","color":"red","w":400},{"type":"line","x1":24,"y1":284,"x2":420,"y2":284,"color":"red","strokeWidth":3},{"type":"image","field":"imageUrl","x":430,"y":220,"w":194,"h":194},{"type":"text","field":"detail1","x":24,"y":316,"fontSize":13,"fontWeight":"normal","align":"left","color":"black","w":390,"maxLines":1},{"type":"text","field":"detail2","x":24,"y":342,"fontSize":13,"fontWeight":"normal","align":"left","color":"black","w":390,"maxLines":1},{"type":"text","field":"detail3","x":24,"y":368,"fontSize":13,"fontWeight":"normal","align":"left","color":"black","w":390,"maxLines":1},{"type":"text","field":"unit","x":24,"y":408,"fontSize":13,"fontWeight":"bold","align":"left","color":"red","w":390},{"type":"text","field":"category","x":24,"y":450,"fontSize":11,"fontWeight":"normal","align":"left","color":"black","w":390}]}');

-- ESL-7.5 — 800×480
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_elt_750','tpl_elite_display','ESL-7.5',800,480,
'{"width":800,"height":480,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":800,"h":76,"color":"red","radius":0},{"type":"rect","x":560,"y":40,"w":180,"h":180,"color":"red","radius":90},{"type":"rect","x":584,"y":64,"w":132,"h":132,"color":"yellow","radius":66},{"type":"badge","field":"discount","x":22,"y":16,"w":150,"h":38,"fontSize":18,"fontWeight":"bold","color":"white","bgColor":"black","radius":19,"paddingX":16,"paddingY":6},{"type":"text","field":"name","x":32,"y":112,"fontSize":26,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":510},{"type":"text","field":"old_price","x":32,"y":160,"fontSize":20,"fontWeight":"normal","align":"left","color":"black","strikethrough":true},{"type":"text","field":"price","x":32,"y":270,"fontSize":76,"fontWeight":"bold","align":"left","color":"red","w":510},{"type":"line","x1":32,"y1":296,"x2":530,"y2":296,"color":"red","strokeWidth":3},{"type":"image","field":"imageUrl","x":540,"y":236,"w":228,"h":210},{"type":"text","field":"detail1","x":32,"y":322,"fontSize":14,"fontWeight":"normal","align":"left","color":"black","w":490,"maxLines":1},{"type":"text","field":"detail2","x":32,"y":348,"fontSize":14,"fontWeight":"normal","align":"left","color":"black","w":490,"maxLines":1},{"type":"text","field":"detail3","x":32,"y":374,"fontSize":14,"fontWeight":"normal","align":"left","color":"black","w":490,"maxLines":1},{"type":"text","field":"unit","x":32,"y":412,"fontSize":14,"fontWeight":"bold","align":"left","color":"red","w":490},{"type":"text","field":"category","x":32,"y":452,"fontSize":12,"fontWeight":"normal","align":"left","color":"black","w":490}]}');

-- ESL-11.6 — 960×640
INSERT INTO template_variants (id, template_id, tag_model, width, height, layout_json) VALUES
('tv_elt_116','tpl_elite_display','ESL-11.6',960,640,
'{"width":960,"height":640,"background":"white","elements":[{"type":"rect","x":0,"y":0,"w":960,"h":90,"color":"red","radius":0},{"type":"rect","x":660,"y":48,"w":220,"h":220,"color":"red","radius":110},{"type":"rect","x":690,"y":78,"w":160,"h":160,"color":"yellow","radius":80},{"type":"badge","field":"discount","x":28,"y":18,"w":170,"h":46,"fontSize":22,"fontWeight":"bold","color":"white","bgColor":"black","radius":23,"paddingX":18,"paddingY":8},{"type":"text","field":"name","x":40,"y":136,"fontSize":32,"fontWeight":"bold","align":"left","color":"black","maxLines":2,"w":600},{"type":"text","field":"old_price","x":40,"y":200,"fontSize":24,"fontWeight":"normal","align":"left","color":"black","strikethrough":true},{"type":"text","field":"price","x":40,"y":342,"fontSize":96,"fontWeight":"bold","align":"left","color":"red","w":600},{"type":"line","x1":40,"y1":374,"x2":630,"y2":374,"color":"red","strokeWidth":3},{"type":"image","field":"imageUrl","x":640,"y":290,"w":280,"h":280},{"type":"text","field":"detail1","x":40,"y":406,"fontSize":17,"fontWeight":"normal","align":"left","color":"black","w":580,"maxLines":1},{"type":"text","field":"detail2","x":40,"y":438,"fontSize":17,"fontWeight":"normal","align":"left","color":"black","w":580,"maxLines":1},{"type":"text","field":"detail3","x":40,"y":470,"fontSize":17,"fontWeight":"normal","align":"left","color":"black","w":580,"maxLines":1},{"type":"text","field":"unit","x":40,"y":520,"fontSize":16,"fontWeight":"bold","align":"left","color":"red","w":580},{"type":"text","field":"category","x":40,"y":598,"fontSize":15,"fontWeight":"normal","align":"left","color":"black","w":580}]}');
